item_type_t BOSS_ITEM_DROPS[][5] = {
	{ IT_POWER, IT_POWER, IT_BIGPOWER, IT_POWER, IT_POWER },
#if GAME == 4
	{ IT_POWER, IT_POWER,    IT_POWER, IT_POWER, IT_POWER },
#endif
	{ IT_POINT, IT_POINT,    IT_POINT, IT_POINT, IT_POINT },
};
