; ReC98
; -----
; Types shared between TH04 and TH05

include defconv_pascal.inc

; Formats
; --------
include th04/formats/bb.inc
include th04/formats/map.inc
; --------

include th04/hardware/grcg.inc
include th04/hardware/input.inc
include th04/math/randring_next.inc
include th04/math/motion.inc
include th02/gaiji/boldfont.inc
include th04/gaiji.inc
include th04/hud/popup.inc
include th02/score.inc
