gs_YINYANG = 002h
gs_BOMB = 003h

include th02/gaiji/boldfont.inc

g_BAR_MAX_0 = 040h
g_BAR_MAX_1 = 041h
g_BAR_MAX_2 = 042h
g_BAR_MAX_3 = 043h
g_BAR_MAX_4 = 044h

gs_Sc = 0C4h
gs_cor = 0C5h
gs_e = 0C6h
gs_REIRYOKU_REI = 0C7h
gs_REIRYOKU_RYOKU = 0C8h
gs_REIMU_REI = 0C9h
gs_REIMU_MU = 0CAh
gs_BLANK = 0CBh
gs_REIGEKI_REI = 0CCh
gs_REIGEKI_GEKI = 0CDh
gs_Hi = 0CEh
gb_SP = 0CFh
gs_BULLET = 0DAh
gs_NOTES = 0D8h
gs_ALL = 0F0h
