;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	AD4E53E1F1A042FBDA82F86B9BD6728C

; File Name   :	th01/OP.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-14040h Loaded length: 13418h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'O'

include ReC98.inc
include th01/th01.inc
include th01/formats/cfg.inc

	extern SCOPY@:proc
	extern __setargv__:proc ; main() needs both to be set
	extern __setenvp__:proc
	extern _atol:proc
	extern _int86:proc
	extern _memcmp:proc
	extern _printf:proc

op_01 group op_01_TEXT, op_01__TEXT

; ===========================================================================

; Segment type:	Pure code
_TEXT		segment	word public 'CODE' use16
		assume cs:_TEXT
		assume es:nothing, ds:DGROUP, fs:nothing, gs:nothing

include libs/master.lib/graph_400line.asm
include libs/master.lib/graph_clear.asm
include libs/master.lib/graph_show.asm
include libs/master.lib/graph_start.asm
include libs/master.lib/palette_show.asm
include libs/master.lib/palette_init.asm
include libs/master.lib/respal_exist.asm
include libs/master.lib/respal_free.asm
include libs/master.lib/resdata.asm
include libs/master.lib/file_read.asm
include libs/master.lib/file_close.asm
include libs/master.lib/file_ropen.asm
include libs/master.lib/file_seek.asm
include libs/master.lib/dos_free.asm
include libs/master.lib/keystart.asm
include libs/master.lib/keybios.asm
include libs/master.lib/dos_ropen.asm
include libs/master.lib/egc.asm
include libs/master.lib/random.asm
_TEXT		ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
op_01_TEXT	segment	byte public 'CODE' use16
op_01_TEXT	ends

op_01__TEXT	segment	byte public 'CODE' use16
		assume cs:op_01
		;org 4
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

	extern @cfg_load$qv:proc
	extern @cfg_save$qv:proc
	extern @main_input_sense$qv:proc
	extern @option_input_sense$qv:proc
	extern @whitelines_animate$qv:proc
	extern @title_init$qv:proc
	extern @title_window_put$qv:proc
	extern @title_exit$qv:proc
	extern @start_game$qv:proc
	extern @start_continue$qv:proc
	extern @title_hit_key_put$qi:proc
	extern @main_choice_unput_and_put$qii:proc
	extern @option_choice_unput_and_put$qii:proc
	extern @music_choice_unput_and_put$qii:proc

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AB97	proc far
		push	bp
		mov	bp, sp
		cmp	word_12564, 0
		jnz	short loc_AC04
		call	@egc_copy_rect_1_to_0_16$qiiii c, large (266 shl 16) or 220, large (100 shl 16) or 176
		call	@main_choice_unput_and_put$qii c, large 0 or (5 shl 16)
		call	@main_choice_unput_and_put$qii c, large 1 or (5 shl 16)
		call	@main_choice_unput_and_put$qii c, large 2 or (5 shl 16)
		call	@main_choice_unput_and_put$qii c, large 3 or (5 shl 16)
		push	15
		mov	al, _menu_sel
		cbw
		push	ax
		call	@main_choice_unput_and_put$qii
		add	sp, 4
		mov	word_12564, 1
		mov	al, _menu_sel
		cbw
		mov	word_12562, ax

loc_AC04:
		mov	al, _menu_sel
		cbw
		cmp	ax, word_12562
		jz	short loc_AC30
		call	@main_choice_unput_and_put$qii c, word_12562, 5
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@main_choice_unput_and_put$qii
		add	sp, 4
		mov	al, _menu_sel
		cbw
		mov	word_12562, ax

loc_AC30:
		cmp	_input_ok, 0
		jnz	short loc_AC3E
		cmp	_input_shot, 0
		jz	short loc_AC6E

loc_AC3E:
		mov	al, _menu_sel
		cbw
		mov	bx, ax
		cmp	bx, 3
		ja	short loc_AC6E
		add	bx, bx
		jmp	cs:off_AC7C[bx]

loc_AC50:
		call	@start_game$qv
		jmp	short loc_AC6E
; ---------------------------------------------------------------------------

loc_AC56:
		call	@start_continue$qv
		jmp	short loc_AC6E
; ---------------------------------------------------------------------------

loc_AC5C:
		mov	byte_1232A, 1
		mov	word_12564, 0
		jmp	short loc_AC6E
; ---------------------------------------------------------------------------

loc_AC69:
		mov	byte_1232C, 1

loc_AC6E:
		cmp	_input_cancel, 0
		jz	short loc_AC7A
		mov	byte_1232C, 1

loc_AC7A:
		pop	bp
		retf
sub_AB97	endp

; ---------------------------------------------------------------------------
off_AC7C	dw offset loc_AC50
		dw offset loc_AC56
		dw offset loc_AC5C
		dw offset loc_AC69

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AC84	proc far
		push	bp
		mov	bp, sp
		cmp	word_12566, 0
		jnz	short loc_ACF9
		mov	_menu_sel, 0
		mov	word_12568, 0
		mov	word_12566, 1
		mov	_option_choice_max, 4
		call	@egc_copy_rect_1_to_0_16$qiiii c, large (276 shl 16) or 220, large (80 shl 16) or 176
		call	@option_choice_unput_and_put$qii c, large 0 or (15 shl 16)
		call	@option_choice_unput_and_put$qii c, large 1 or (5 shl 16)
		call	@option_choice_unput_and_put$qii c, large 2 or (5 shl 16)
		call	@option_choice_unput_and_put$qii c, large 3 or (5 shl 16)
		call	@option_choice_unput_and_put$qii c, large 4 or (5 shl 16)

loc_ACF9:
		mov	al, _menu_sel
		cbw
		cmp	ax, word_12568
		jz	short loc_AD25
		call	@option_choice_unput_and_put$qii c, word_12568, 5
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@option_choice_unput_and_put$qii
		add	sp, 4
		mov	al, _menu_sel
		cbw
		mov	word_12568, ax

loc_AD25:
		mov	al, _input_left
		cbw
		cmp	ax, 1
		jnz	short loc_AD96
		cmp	word_1256A, 0
		jnz	short loc_AD9C
		mov	al, _menu_sel
		cbw
		or	ax, ax
		jz	short loc_AD49
		cmp	ax, 1
		jz	short loc_AD5C
		cmp	ax, 2
		jz	short loc_AD6F
		jmp	short loc_AD80
; ---------------------------------------------------------------------------

loc_AD49:
		dec	_opts.O_rank
		mov	al, _opts.O_rank
		cbw
		or	ax, ax
		jge	short loc_AD80
		mov	_opts.O_rank, RANK_LUNATIC
		jmp	short loc_AD80
; ---------------------------------------------------------------------------

loc_AD5C:
		dec	_opts.O_bgm_mode
		mov	al, _opts.O_bgm_mode
		cbw
		or	ax, ax
		jge	short loc_AD80
		mov	_opts.O_bgm_mode, 1
		jmp	short loc_AD80
; ---------------------------------------------------------------------------

loc_AD6F:
		dec	_opts.O_lives_extra
		mov	al, _opts.O_lives_extra
		cbw
		or	ax, ax
		jge	short loc_AD80
		mov	_opts.O_lives_extra, (CFG_LIVES_EXTRA_MAX - 1)

loc_AD80:
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@option_choice_unput_and_put$qii
		add	sp, 4
		mov	word_1256A, 1
		jmp	short loc_AD9C
; ---------------------------------------------------------------------------

loc_AD96:
		mov	word_1256A, 0

loc_AD9C:
		mov	al, _input_right
		cbw
		cmp	ax, 1
		jnz	short loc_AE10
		cmp	word_1256C, 0
		jnz	short loc_AE16
		mov	al, _menu_sel
		cbw
		or	ax, ax
		jz	short loc_ADC0
		cmp	ax, 1
		jz	short loc_ADD4
		cmp	ax, 2
		jz	short loc_ADE8
		jmp	short loc_ADFA
; ---------------------------------------------------------------------------

loc_ADC0:
		inc	_opts.O_rank
		mov	al, _opts.O_rank
		cbw
		cmp	ax, RANK_LUNATIC
		jle	short loc_ADFA
		mov	_opts.O_rank, RANK_EASY
		jmp	short loc_ADFA
; ---------------------------------------------------------------------------

loc_ADD4:
		inc	_opts.O_bgm_mode
		mov	al, _opts.O_bgm_mode
		cbw
		cmp	ax, 1
		jle	short loc_ADFA
		mov	_opts.O_bgm_mode, 0
		jmp	short loc_ADFA
; ---------------------------------------------------------------------------

loc_ADE8:
		inc	_opts.O_lives_extra
		mov	al, _opts.O_lives_extra
		cbw
		cmp	ax, (CFG_LIVES_EXTRA_MAX - 1)
		jle	short loc_ADFA
		mov	_opts.O_lives_extra, 0

loc_ADFA:
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@option_choice_unput_and_put$qii
		add	sp, 4
		mov	word_1256C, 1
		jmp	short loc_AE16
; ---------------------------------------------------------------------------

loc_AE10:
		mov	word_1256C, 0

loc_AE16:
		cmp	_input_ok, 0
		jnz	short loc_AE24
		cmp	_input_shot, 0
		jz	short loc_AE2D

loc_AE24:
		mov	al, _menu_sel
		cbw
		cmp	ax, 4
		jz	short loc_AE34

loc_AE2D:
		cmp	_input_cancel, 0
		jz	short loc_AE44

loc_AE34:
		mov	byte_1232A, 3
		mov	word_12566, 0
		mov	_menu_sel, 2

loc_AE44:
		cmp	_input_ok, 0
		jnz	short loc_AE52
		cmp	_input_shot, 0
		jz	short loc_AE6B

loc_AE52:
		mov	al, _menu_sel
		cbw
		cmp	ax, 3
		jnz	short loc_AE6B
		mov	byte_1232A, 2
		mov	word_12566, 0
		mov	_menu_sel, 0

loc_AE6B:
		pop	bp
		retf
sub_AC84	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AE6D	proc far

var_3C		= byte ptr -3Ch

		enter	3Ch, 0
		lea	ax, [bp+var_3C]
		push	ss
		push	ax
		push	ds
		push	offset _MUSIC_FILES
		mov	cx, 3Ch	; '<'
		call	SCOPY@
		call	@mdrv2_bgm_stop$qv
		mov	al, _music_sel
		cbw
		shl	ax, 2
		lea	dx, [bp+var_3C]
		add	ax, dx
		mov	bx, ax
		pushd	dword ptr ss:[bx]	; path
		call	@mdrv2_bgm_load$qnxc
		add	sp, 4
		call	@mdrv2_bgm_play$qv
		leave
		retf
sub_AE6D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AEA8	proc far
		push	bp
		mov	bp, sp
		cmp	word_125AA, 0
		jnz	short loc_AF00
		mov	_menu_sel, 0
		mov	word_125AC, 0
		mov	word_125AA, 1
		mov	_input_ok, 0
		mov	_input_shot, 0
		mov	_option_choice_max, 1
		call	@egc_copy_rect_1_to_0_16$qiiii c, large (266 shl 16) or 220, large (100 shl 16) or 176
		call	@music_choice_unput_and_put$qii c, large 0 or (15 shl 16)
		call	@music_choice_unput_and_put$qii c, large 1 or (5 shl 16)

loc_AF00:
		mov	al, _menu_sel
		cbw
		cmp	ax, word_125AC
		jz	short loc_AF2C
		call	@music_choice_unput_and_put$qii c, word_125AC, 5
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@music_choice_unput_and_put$qii
		add	sp, 4
		mov	al, _menu_sel
		cbw
		mov	word_125AC, ax

loc_AF2C:
		mov	al, _input_left
		cbw
		cmp	ax, 1
		jnz	short loc_AF69
		cmp	word_125AE, 0
		jnz	short loc_AF6F
		cmp	_menu_sel, 0
		jnz	short loc_AF53
		dec	_music_sel
		cmp	_music_sel, 0
		jge	short loc_AF53
		mov	_music_sel, 0Eh

loc_AF53:
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@music_choice_unput_and_put$qii
		add	sp, 4
		mov	word_125AE, 1
		jmp	short loc_AF6F
; ---------------------------------------------------------------------------

loc_AF69:
		mov	word_125AE, 0

loc_AF6F:
		mov	al, _input_right
		cbw
		cmp	ax, 1
		jnz	short loc_AFAC
		cmp	word_125B0, 0
		jnz	short loc_AFB2
		cmp	_menu_sel, 0
		jnz	short loc_AF96
		inc	_music_sel
		cmp	_music_sel, 0Fh
		jl	short loc_AF96
		mov	_music_sel, 0

loc_AF96:
		push	0Fh
		mov	al, _menu_sel
		cbw
		push	ax
		call	@music_choice_unput_and_put$qii
		add	sp, 4
		mov	word_125B0, 1
		jmp	short loc_AFB2
; ---------------------------------------------------------------------------

loc_AFAC:
		mov	word_125B0, 0

loc_AFB2:
		cmp	_input_ok, 0
		jnz	short loc_AFC0
		cmp	_input_shot, 0
		jz	short loc_AFC9

loc_AFC0:
		mov	al, _menu_sel
		cbw
		cmp	ax, 1
		jz	short loc_AFD0

loc_AFC9:
		cmp	_input_cancel, 0
		jz	short loc_AFE0

loc_AFD0:
		mov	byte_1232A, 4
		mov	word_125AA, 0
		mov	_menu_sel, 3

loc_AFE0:
		cmp	_input_ok, 0
		jnz	short loc_AFEE
		cmp	_input_shot, 0
		jz	short loc_AFF9

loc_AFEE:
		cmp	_menu_sel, 0
		jnz	short loc_AFF9
		call	sub_AE6D

loc_AFF9:
		pop	bp
		retf
sub_AEA8	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int argc, const char	**argv,	const char **envp)
public _main
_main		proc far

outregs		= REGS ptr -2Ch
inregs		= REGS ptr -1Ch
@@kb_buf		= word ptr -0Ch
var_9		= byte ptr -9
var_8		= dword	ptr -8
var_4		= dword	ptr -4
_argc		= word ptr  4
_argv		= dword	ptr  6
_envp		= dword	ptr  0Ah

		enter	2Ch, 0
		push	si
		push	di
		xor	si, si
		xor	di, di
		call	@mdrv2_resident$qv
		or	ax, ax
		jnz	short loc_B015
		push	ds
		push	offset aGogbgGtg@gcglv ; "ƒoƒbƒ`ƒtƒ@ƒCƒ‹‚©‚ç‹N“®‚µ‚Ä‚æ"
		jmp	loc_B25D
; ---------------------------------------------------------------------------

loc_B015:
		mov	byte_1232D, 0
		mov	dword_12330, 0
		mov	byte_1232E, 0
		cmp	word ptr [bp+_argv], 1
		jle	loc_B0D6
		les	bx, [bp+_argv+2]
		les	bx, es:[bx+4]
		mov	al, es:[bx]
		cbw
		cmp	ax, 73h	; 's'
		jnz	short loc_B045
		mov	_debug_mode, 1

loc_B045:
		les	bx, [bp+_argv+2]
		les	bx, es:[bx+4]
		mov	al, es:[bx]
		cbw
		cmp	ax, 74h	; 't'
		jnz	short loc_B05A
		mov	_debug_mode, 2

loc_B05A:
		les	bx, [bp+_argv+2]
		les	bx, es:[bx+4]
		mov	al, es:[bx]
		cbw
		cmp	ax, 64h	; 'd'
		jnz	short loc_B06F
		mov	_debug_mode, 3

loc_B06F:
		push	3		; n
		push	ds
		push	offset aCon	; "CON"
		les	bx, [bp+_argv+2]
		pushd	dword ptr es:[bx+4] ; s1
		call	_memcmp
		add	sp, 0Ah
		or	ax, ax
		jnz	short loc_B0D6
		les	bx, [bp+_argv+2]
		mov	eax, es:[bx+8]
		mov	[bp+var_4], eax
		pushd	[bp+var_4]
		call	_atol
		add	sp, 4
		mov	byte_1232D, al
		les	bx, [bp+_argv+2]
		pushd	dword ptr es:[bx+0Ch]
		call	_atol
		add	sp, 4
		mov	word ptr dword_12330+2,	dx
		mov	word ptr dword_12330, ax
		les	bx, [bp+_argv+2]
		mov	eax, es:[bx+10h]
		mov	[bp+var_8], eax
		pushd	[bp+var_8]
		call	_atol
		add	sp, 4
		mov	byte_1232E, al

loc_B0D6:
		call	@mdrv2_check_board$qv
		call	@game_init$qv
		call	@cfg_load$qv
		mov	al, _opts.O_bgm_mode
		cbw
		mov	si, ax
		mov	byte ptr [bp+inregs+1],	3
		push	ss
		lea	ax, [bp+outregs]
		push	ax		; outregs
		push	ss
		lea	ax, [bp+inregs]
		push	ax		; inregs
		push	18h		; intno
		call	_int86
		add	sp, 0Ah
		call	key_start
		call	@title_init$qv
		xor	ax, ax
		mov	es, ax
		mov	al, es:((50h shl 4) + 00h) ; BIOS_FLAG
		or	al, 20h ; Do not beep when key buffer overflows
		mov	[bp+var_9], al
		xor	ax, ax
		mov	dl, [bp+var_9]
		mov	es, ax
		mov	es:((50h shl 4) + 00h), dl  ; BIOS_FLAG
		jmp	short loc_B135
; ---------------------------------------------------------------------------

loc_B126:
		push	1
		call	@frame_delay$qui
		pop	cx
		call	@title_hit_key_put$qi stdcall, di
		pop	cx
		inc	di

loc_B135:
		call	key_sense_bios
		or	ax, ax
		jz	short loc_B126
		call	@title_window_put$qv
		mov	eax, _rand
		mov	random_seed, eax
		jmp	loc_B21A
; ---------------------------------------------------------------------------

loc_B14D:
		cmp	byte_1232A, 0
		jnz	short loc_B15F
		call	@main_input_sense$qv
		call	sub_AB97
		jmp	loc_B1EE
; ---------------------------------------------------------------------------

loc_B15F:
		mov	al, byte_1232A
		cbw
		cmp	ax, 1
		jnz	short loc_B172
		call	@option_input_sense$qv
		call	sub_AC84
		jmp	short loc_B1EE
; ---------------------------------------------------------------------------

loc_B172:
		mov	al, byte_1232A
		cbw
		cmp	ax, 2
		jnz	short loc_B185
		call	@option_input_sense$qv
		call	sub_AEA8
		jmp	short loc_B1EE
; ---------------------------------------------------------------------------

loc_B185:
		mov	al, byte_1232A
		cbw
		cmp	ax, 3
		jnz	short loc_B1D8
		mov	al, _opts.O_bgm_mode
		cbw
		cmp	ax, si
		jz	short loc_B1C9
		cmp	_opts.O_bgm_mode, 0
		jnz	short loc_B1A4
		call	@mdrv2_bgm_stop$qv
		jmp	short loc_B1C3
; ---------------------------------------------------------------------------

loc_B1A4:
		mov	al, _opts.O_bgm_mode
		cbw
		cmp	ax, 1
		jnz	short loc_B1C3
		call	@mdrv2_bgm_stop$qv
		push	ds
		push	offset _aReimu_mdt ; "reimu.mdt"
		call	@mdrv2_bgm_load$qnxc
		add	sp, 4
		call	@mdrv2_bgm_play$qv

loc_B1C3:
		mov	al, _opts.O_bgm_mode
		cbw
		mov	si, ax

loc_B1C9:
		push	0Fh
		call	@frame_delay$qui
		pop	cx
		mov	byte_1232A, 0
		jmp	short loc_B1EE
; ---------------------------------------------------------------------------

loc_B1D8:
		mov	al, byte_1232A
		cbw
		cmp	ax, 4
		jnz	short loc_B1EE
		push	0Fh
		call	@frame_delay$qui
		pop	cx
		mov	byte_1232A, 1

loc_B1EE:
		xor	ax, ax
		mov	es, ax
		mov	ax, word ptr es:[((50h shl 4) + 24h)] ; KB_BUF_HEAD
		mov	[bp+@@kb_buf], ax
		xor	ax, ax
		mov	dx, [bp+@@kb_buf]
		mov	es, ax
		mov	word ptr es:[((50h shl 4) + 26h)], dx ; KB_BUF_TAIL
		mov	es, ax
		mov	byte ptr es:[((50h shl 4) + 28h)], 0 ; KB_COUNT
		inc	_rand
		push	1
		call	@frame_delay$qui
		pop	cx

loc_B21A:
		cmp	byte_1232C, 0
		jz	loc_B14D
		call	@cfg_save$qv
		mov	_free_resident_structure_on_title, 1
		call	@mdrv2_bgm_stop$qv
		call	@title_exit$qv
		push	1
		call	@graph_accesspage_func$qi
		pop	cx
		call	@z_graph_clear$qv
		push	0
		call	@graph_accesspage_func$qi
		pop	cx
		call	@z_graph_clear$qv
		call	@game_exit$qv
		call	@mdrv2_bgm_stop$qv
		push	ds
		push	offset format	; "‚¨‚Â‚©‚ê‚³‚Ü‚Å‚µ‚½II\n"

loc_B25D:
		call	_printf
		add	sp, 4
		pop	di
		pop	si
		leave
		retf
_main		endp
op_01__TEXT	ends

; ===========================================================================

; Segment type:	Pure code
frmdelay_TEXT	segment	byte public 'CODE' use16
	extern @frame_delay$qui:proc
frmdelay_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
vsync_TEXT	segment	byte public 'CODE' use16
vsync_TEXT	ends

; ===========================================================================

ztext_TEXT	segment	byte public 'CODE' use16
ztext_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
initexit_TEXT	segment	byte public 'CODE' use16
	extern @game_init$qv:proc
	extern @game_exit$qv:proc
initexit_TEXT	ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
graph_TEXT	segment	byte public 'CODE' use16
	extern @graph_accesspage_func$qi:proc
	extern @z_graph_clear$qv:proc
graph_TEXT	ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
SHARED	segment	byte public 'CODE' use16
	extern @egc_copy_rect_1_to_0_16$qiiii:proc
SHARED	ends

; ===========================================================================

; Segment type:	Pure code
grppffx_TEXT	segment	byte public 'CODE'
grppffx_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
PTN_GRP_GRZ	segment	byte public 'CODE' use16
PTN_GRP_GRZ	ends

; ===========================================================================

; Segment type:	Pure code
resstuff_TEXT	segment	byte public 'CODE'
resstuff_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
mdrv2_TEXT	segment	byte public 'CODE' use16
	extern @mdrv2_resident$qv:proc
	extern @mdrv2_bgm_load$qnxc:proc
	extern @mdrv2_bgm_play$qv:proc
	extern @mdrv2_bgm_stop$qv:proc
	extern @mdrv2_check_board$qv:proc
mdrv2_TEXT	ends

; ===========================================================================

op_12_TEXT	segment	byte public 'CODE' use16
op_12_TEXT	ends

; ===========================================================================

	.data

	extern _opts:cfg_options_t
	extern _debug_mode:byte
	extern _menu_sel:byte
	extern _input_left:byte
	extern _input_ok:byte
	extern _input_shot:byte
	extern _input_cancel:byte
	extern byte_1232A:byte
	extern _input_right:byte
	extern byte_1232C:byte
	extern byte_1232D:byte
	extern byte_1232E:byte
	extern _free_resident_structure_on_title:byte
	extern dword_12330:dword
	extern _option_choice_max:byte

		db 0

public _MAIN_CHOICES
_MAIN_CHOICES	label dword
	dd aVrvsvVqvs	; "   ‚r‚s‚`‚q‚s   "
	dd aVbvnvmvsvhvmvt	; "‚b‚n‚m‚s‚h‚m‚t‚d"
	dd aB@vnvovsvhvnvm	; "@‚n‚o‚s‚h‚n‚m@"
	dd aB@b@vpvtvhvsb@	; "@@‚p‚t‚h‚s@@"

public _OPTION_CHOICES, _RANK_VALUES, _BGM_MODE_VALUES, _START_LIFE_VALUES
_OPTION_CHOICES label dword
	dd aB@vqvVmvjb@	; "@‚q‚`‚m‚j@	"
	dd aVlvtvrvhvb	; " ‚l‚t‚r‚h‚b	"
	dd aVovkvVxvdvq	; "‚o‚k‚`‚x‚d‚q	"
	dd aVlbdvsvdvrvs	; "‚lD‚s‚d‚r‚s	"
	dd aB@vpvtvhvsb@	; "@‚p‚t‚h‚s@	"
_RANK_VALUES label dword
	dd aEasy	; " EASY "
	dd aNormal		; "NORMAL"
	dd aHard		; " HARD "
	dd aLunatic		; "LUNATIC"
_BGM_MODE_VALUES	label dword
	dd aOff	; "  OFF "
	dd aFm	; "  FM	 "
_START_LIFE_VALUES	label dword
	dd a3	; "   3	 "
	dd a4	; "   4	 "
	dd a5	; "   5	 "
	dd a6	; "   6	 "
	dd a7	; "   7	 "

public _music_sel
_music_sel	db 0

public _MUSIC_CHOICES
_MUSIC_CHOICES label dword
	dd aVlvtvrvhvbb@vm	; "‚l‚t‚r‚h‚b@‚m‚D"
	dd aB@b@vpvxvivf	; "@@‚p‚•‚‰‚”	     "

public _MUSIC_TITLES
_MUSIC_TITLES	label dword
	dd aASacretLot	; "    A Sacret	Lot"
	dd aXcvR_o	; "	 •—‚Ì_ŽÐ     "
	dd aIiiuvIPc	; "	‰i‰“‚Ì›Þ—    "
	dd aHighlyResponsi	; "  Highly Responsive"
	dd aUmx
	dd aOrientalMagici	; "  Oriental Magician"
	dd aB@FjoVPmsUbb@	; "@  ”jŽ×‚Ì¬‘¾“@ "
	dd aTheLegendOfKag	; " The Legend of KAGE"
	dd aPositiveAndNeg	; "Positive and	Negative"
	dd aB@b@UvoguRrb@b	; "@@	 “VŽg“`à@@ "
	dd aB@b@b@CvlB@b@b	; "@@@  –‚‹¾@@@ "
	dd aVvvUVRVnvVOuvV	; "‚¢‚´“|‚êÀ‚­‚»‚ÌŽž‚Ü‚Å"
	dd aB@b@oavVVrvivV	; "@@Ž€‚È‚Î‚à‚ë‚Æ‚à@@"
	dd aB@b@Rpchmxom	; "@@	 ¯—HŒ•Žm"
	dd aB@b@b@gagcgkgx	; "@@@ƒAƒCƒŠƒX"

word_12562	dw 63h
word_12564	dw 0
word_12566	dw 0
word_12568	dw 0
word_1256A	dw 0
word_1256C	dw 0

public _MUSIC_FILES
_MUSIC_FILES	label dword
	dd _aReimu_mdt	; "reimu.mdt"
	dd aZipangu_mdt		; "ZIPANGU.mdt"
	dd aSt0_mdt		; "st0.mdt"
	dd aSt1_mdt		; "st1.mdt"
	dd aSt2_mdt		; "st2.mdt"
	dd aSt3_mdt		; "st3.mdt"
	dd aSt4_mdt		; "st4.mdt"
	dd aSt5_mdt		; "st5.mdt"
	dd aPositive_mdt	; "positive.mdt"
	dd aLegend_mdt		; "legend.mdt"
	dd aKami_mdt		; "kami.mdt"
	dd aTensi_mdt		; "tensi.mdt"
	dd aSyugen_mdt		; "syugen.mdt"
	dd aAlice_mdt		; "alice.mdt"
	dd aIris_mdt		; "iris.mdt"

word_125AA	dw 0
word_125AC	dw 0
word_125AE	dw 0
word_125B0	dw 0
include th01/formats/cfg[data].asm
; char _aReimu_mdt[]
public _aReimu_mdt, _aReiiden2_grp, _aReiiden3_grp, _aOp_win_grp
_aReimu_mdt	db 'reimu.mdt',0
_aReiiden2_grp	db 'REIIDEN2.grp',0
_aReiiden3_grp	db 'REIIDEN3.grp',0
_aOp_win_grp	db 'op_win.grp',0

public _aReiiden_0
_aReiiden_0	db 'reiiden',0

public _GP_HIT_KEY
_GP_HIT_KEY	db ' ‚g‚h‚s@‚j‚d‚x',0
aVrvsvVqvs	db '   ‚r‚s‚`‚q‚s   ',0
aVbvnvmvsvhvmvt	db '‚b‚n‚m‚s‚h‚m‚t‚d',0
aB@vnvovsvhvnvm	db '@‚n‚o‚s‚h‚n‚m@',0
aB@b@vpvtvhvsb@	db '@@‚p‚t‚h‚s@@',0
aB@vqvVmvjb@	db '@‚q‚`‚m‚j@ ',0
aVlvtvrvhvb	db ' ‚l‚t‚r‚h‚b  ',0
aVovkvVxvdvq	db '‚o‚k‚`‚x‚d‚q ',0
aVlbdvsvdvrvs	db '‚lD‚s‚d‚r‚s ',0
aB@vpvtvhvsb@	db '@‚p‚t‚h‚s@ ',0
aEasy		db ' EASY ',0
aNormal		db 'NORMAL',0
aHard		db ' HARD ',0
aLunatic	db 'LUNATIC',0
aOff		db '  OFF ',0
aFm		db '  FM  ',0
a3		db '   3  ',0
a4		db '   4  ',0
a5		db '   5  ',0
a6		db '   6  ',0
a7		db '   7  ',0
; char aSS[]
public _aSS
_aSS		db '%s%s',0
aVlvtvrvhvbb@vm	db '‚l‚t‚r‚h‚b@‚m‚D',0
aB@b@vpvxvivf	db '@@‚p‚•‚‰‚”      ',0
aASacretLot	db '    A Sacret Lot',0
aXcvR_o		db '      •—‚Ì_ŽÐ     ',0
aIiiuvIPc	db '     ‰i‰“‚Ì›Þ—    ',0
aHighlyResponsi	db '  Highly Responsive',0
aUmx		db '     “Œ•û‰öŠï’k    ',0
aOrientalMagici	db '  Oriental Magician',0
aB@FjoVPmsUbb@	db '@  ”jŽ×‚Ì¬‘¾“@ ',0
aTheLegendOfKag	db ' The Legend of KAGE',0
aPositiveAndNeg	db 'Positive and Negative',0
aB@b@UvoguRrb@b	db '@@  “VŽg“`à@@ ',0
aB@b@b@CvlB@b@b	db '@@@  –‚‹¾@@@ ',0
aVvvUVRVnvVOuvV	db '‚¢‚´“|‚êÀ‚­‚»‚ÌŽž‚Ü‚Å',0
aB@b@oavVVrvivV	db '@@Ž€‚È‚Î‚à‚ë‚Æ‚à@@',0
aB@b@Rpchmxom	db '@@  ¯—HŒ•Žm',0
aB@b@b@gagcgkgx	db '@@@ƒAƒCƒŠƒX',0

public _aS_2d
_aS_2d		db '%s%.2d',0
aZipangu_mdt	db 'ZIPANGU.mdt',0
aSt0_mdt	db 'st0.mdt',0
aSt1_mdt	db 'st1.mdt',0
aSt2_mdt	db 'st2.mdt',0
aSt3_mdt	db 'st3.mdt',0
aSt4_mdt	db 'st4.mdt',0
aSt5_mdt	db 'st5.mdt',0
aPositive_mdt	db 'positive.mdt',0
aLegend_mdt	db 'legend.mdt',0
aKami_mdt	db 'kami.mdt',0
aTensi_mdt	db 'tensi.mdt',0
aSyugen_mdt	db 'syugen.mdt',0
aAlice_mdt	db 'alice.mdt',0
aIris_mdt	db 'iris.mdt',0
aGogbgGtg@gcglv	db 'ƒoƒbƒ`ƒtƒ@ƒCƒ‹‚©‚ç‹N“®‚µ‚Ä‚æ',0
aCon		db 'CON',0
; char format[]
format		db '‚¨‚Â‚©‚ê‚³‚Ü‚Å‚µ‚½II',0Ah,0

	; libs/master.lib/grp[data].asm
	extern graph_VramSeg:word
	extern graph_VramWords:word
	extern graph_VramLines:word
	extern graph_VramZoom:word

	; libs/master.lib/pal[data].asm
	extern PaletteTone:word
	extern PalettesInit:rgb_t:COLOR_COUNT
	extern PaletteNote:word
	extern ResPalSeg:word

	; libs/master.lib/respal_exist[data].asm
IDLEN EQU 10
	extern ResPalID:byte:IDLEN

	; libs/master.lib/fil[data].asm
	extern file_BufferSize:word
	extern file_Handle:word

	; libs/master.lib/keytable[data].asm
	extern key_table_normal:word
	extern key_table_shift:word
	extern key_table_ctrl:word
	extern key_table_alt:word

	; libs/master.lib/keystart[data].asm
	extern key_started:word

	; libs/master.lib/keyback[data].asm
	extern key_back_buffer:word

	; libs/master.lib/dos_ropen[data].asm
	extern file_sharingmode:word

	; libs/master.lib/clip[data].asm
	extern ClipXL:word
	extern ClipXW:word
	extern ClipXR:word
	extern ClipYT:word
	extern ClipYH:word
	extern ClipYB:word
	extern ClipYT_seg:word
	extern ClipYB_adr:word

	; libs/master.lib/rand[data].asm
	extern random_seed:dword

	.data?

public _rand
_rand	dd ?
public _columns
_columns	dd ROW_SIZE dup (?)

	; libs/master.lib/pal[bss].asm
	extern Palettes:rgb_t:COLOR_COUNT

	; libs/master.lib/fil[bss].asm
	extern file_Buffer:dword
	extern file_BufferPos:dword
	extern file_BufPtr:word
	extern file_InReadBuf:word
	extern file_Eof:word
	extern file_ErrorStat:word

	; libs/master.lib/keystart[bss].asm
	extern key_backup:byte:786
	extern keywork:byte:10

		end
