;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	DE5454973591EBD937B11452A8B4882D

; File Name   :	th01/ZUNSOFT.COM
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-2870h Loaded length: 2770h
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model tiny
		DGROUP group seg000

include ReC98.inc

; ===========================================================================

; Segment type:	Pure code
seg000		segment	word public 'CODE' use16
		assume cs:seg000
		org 100h
		assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing

include libs/BorlandC/c0.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_367		proc near
		push	bp
		mov	bp, sp
		mov	dx, 0A6h
		mov	al, 1
		out	dx, al		; Interrupt Controller #2, 8259A
		call	graph_clear
		mov	dx, 0A6h
		mov	al, 0
		out	dx, al		; Interrupt Controller #2, 8259A
		call	graph_clear
		mov	dx, 0A4h
		mov	al, 0
		out	dx, al		; Interrupt Controller #2, 8259A
		pop	bp
		retn
sub_367		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_384		proc near
		push	bp
		mov	bp, sp
		call	mem_assign_all
		call	sub_958
		call	key_beep_off
		call	text_systemline_hide
		call	text_cursor_hide
		call	egc_start
		call	sub_367
		call	text_clear
		mov	byte ptr ds:2870h, 0
		mov	byte ptr ds:2871h, 1
		push	60h
		push	64h
		push	21Fh
		push	12Bh
		call	sub_139C
		call	sub_94C
		push	21CEh
		call	super_entry_bfnt
		call	palette_show
		mov	PaletteTone, 0
		call	palette_show
		call	graph_show
		pop	bp
		retn
sub_384		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_3D0		proc near
		push	bp
		mov	bp, sp
		call	super_free
		call	sub_367
		call	sub_136A
		call	text_clear
		call	egc_start
		pop	bp
		retn
sub_3D0		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_3E4		proc near

arg_0		= word ptr  4
arg_2		= byte ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah

		push	bp
		mov	bp, sp
		push	si
		push	di
		mov	si, [bp+arg_6]
		mov	di, [bp+arg_4]
		mov	ax, [bp+arg_0]
		cwd
		mov	bl, [bp+arg_2]
		mov	bh, 0
		and	bx, 0FFh
		add	bx, bx
		push	ax
		mov	ax, [bx+2368h]
		push	dx
		cwd
		pop	cx
		pop	bx
		call	N_LXMUL@
		mov	cl, 8
		call	near ptr N_LXRSH@
		mov	[si], ax
		mov	ax, [bp+arg_0]
		cwd
		mov	bl, [bp+arg_2]
		mov	bh, 0
		and	bx, 0FFh
		add	bx, bx
		push	ax
		mov	ax, [bx+22E8h]
		push	dx
		cwd
		pop	cx
		pop	bx
		call	N_LXMUL@
		mov	cl, 8
		call	near ptr N_LXRSH@
		mov	[di], ax
		pop	di
		pop	si
		pop	bp
		retn	8
sub_3E4		endp ; sp-analysis failed


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_439		proc near
		push	bp
		mov	bp, sp
		push	si
		mov	word ptr ds:2878h, 80h
		mov	word ptr ds:2952h, 0FFF8h
		mov	word ptr ds:287Ah, 140h
		mov	word ptr ds:295Ah, 8
		mov	word ptr ds:287Ch, 100h

loc_45B:
		mov	word ptr ds:2954h, 0FFF8h
		mov	word ptr ds:287Eh, 0F0h
		mov	word ptr ds:295Ch, 8
		mov	word ptr ds:2880h, 180h
		mov	word ptr ds:2956h, 0FFF8h
		mov	word ptr ds:2882h, 0A0h
		mov	word ptr ds:295Eh, 8
		mov	word ptr ds:2884h, 200h
		mov	word ptr ds:2958h, 0FFF8h
		mov	word ptr ds:2886h, 50h
		mov	word ptr ds:2960h, 8
		mov	word ptr ds:2950h, 0
		mov	byte ptr ds:2872h, 0
		mov	byte ptr ds:2873h, 0
		mov	byte ptr ds:2874h, 17h
		mov	byte ptr ds:2875h, 0
		mov	byte ptr ds:2876h, 0
		xor	si, si
		jmp	short loc_4F5
; ---------------------------------------------------------------------------

loc_4C0:
		call	sub_16B2
		mov	bx, 280h
		cwd
		idiv	bx
		mov	bx, si
		shl	bx, 2
		mov	[bx+2888h], dx
		call	sub_16B2
		mov	bx, 190h
		cwd
		idiv	bx
		mov	bx, si
		shl	bx, 2
		mov	[bx+288Ah], dx
		call	sub_16B2
		mov	bx, 20h
		cwd
		idiv	bx
		add	dl, 6
		mov	[si+2963h], dl
		inc	si

loc_4F5:
		cmp	si, 32h
		jl	short loc_4C0
		mov	byte ptr ds:2962h, 40h
		pop	si

loc_500:
		pop	bp
		retn
sub_439		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_502		proc near
		push	bp
		mov	bp, sp
		push	si
		mov	si, 3
		jmp	loc_5A6
; ---------------------------------------------------------------------------

loc_50C:
		push	0C0h
		mov	al, [si+21D9h]
		cbw
		push	ax
		call	grcg_setcolor
		mov	bx, si
		shl	bx, 2
		push	word ptr [bx+2878h]
		mov	bx, si
		shl	bx, 2
		push	word ptr [bx+287Ah]
		push	60h
		call	sub_1588
		mov	bx, si
		add	bx, bx
		mov	ax, [bx+2952h]
		mov	bx, si
		shl	bx, 2
		add	[bx+2878h], ax
		mov	bx, si
		add	bx, bx
		mov	ax, [bx+295Ah]
		mov	bx, si
		shl	bx, 2
		add	[bx+287Ah], ax
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+2878h], 20h
		jle	short loc_56A
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+2878h], 25Fh
		jle	short loc_57B

loc_56A:
		mov	bx, si
		add	bx, bx
		mov	dx, 0FFFFh
		mov	ax, [bx+2952h]
		imul	dx
		mov	[bx+2952h], ax

loc_57B:
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+287Ah], 20h
		jle	short loc_594
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+287Ah], 16Fh
		jle	short loc_5A5

loc_594:
		mov	bx, si
		add	bx, bx
		mov	dx, 0FFFFh
		mov	ax, [bx+295Ah]
		imul	dx
		mov	[bx+295Ah], ax

loc_5A5:
		dec	si

loc_5A6:
		or	si, si
		jl	short loc_5AD
		jmp	loc_50C
; ---------------------------------------------------------------------------

loc_5AD:
		mov	dx, 7Ch
		mov	al, 0
		out	dx, al
		pop	si
		pop	bp
		retn
sub_502		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_5B6		proc near

var_4		= word ptr -4
var_2		= word ptr -2

		enter	4, 0
		push	si
		push	0C0h
		push	5
		call	grcg_setcolor
		xor	si, si
		jmp	loc_66E
; ---------------------------------------------------------------------------

loc_5C8:
		mov	bx, si
		shl	bx, 2
		push	word ptr [bx+2888h]
		mov	bx, si
		shl	bx, 2
		push	word ptr [bx+288Ah]
		call	sub_14E4
		lea	ax, [bp+var_2]
		push	ax
		lea	ax, [bp+var_4]
		push	ax
		push	word ptr ds:2962h
		mov	al, [si+2963h]
		mov	ah, 0
		push	ax
		call	sub_3E4
		mov	bx, si
		shl	bx, 2
		mov	ax, [bp+var_2]
		add	[bx+2888h], ax
		mov	bx, si
		shl	bx, 2
		mov	ax, [bp+var_4]
		add	[bx+288Ah], ax
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+2888h], 0
		jge	short loc_624
		mov	bx, si
		shl	bx, 2
		add	word ptr [bx+2888h], 280h
		jmp	short loc_63C
; ---------------------------------------------------------------------------

loc_624:
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+2888h], 280h
		jl	short loc_63C
		mov	bx, si
		shl	bx, 2
		sub	word ptr [bx+2888h], 280h

loc_63C:
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+288Ah], 0
		jge	short loc_655
		mov	bx, si
		shl	bx, 2
		add	word ptr [bx+288Ah], 190h
		jmp	short loc_66D
; ---------------------------------------------------------------------------

loc_655:
		mov	bx, si
		shl	bx, 2
		cmp	word ptr [bx+288Ah], 190h
		jl	short loc_66D
		mov	bx, si
		shl	bx, 2
		sub	word ptr [bx+288Ah], 190h

loc_66D:
		inc	si

loc_66E:
		cmp	si, 32h
		jge	short loc_676
		jmp	loc_5C8
; ---------------------------------------------------------------------------

loc_676:
		inc	byte ptr ds:2962h
		mov	dx, 7Ch
		mov	al, 0
		out	dx, al
		pop	si
		leave
		retn
sub_5B6		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_683		proc near
		push	bp
		mov	bp, sp

loc_686:
		out	5Fh, al
		in	al, 0A0h	; PIC 2	 same as 0020 for PIC 1
		test	al, 20h
		jnz	short loc_686

loc_68E:
		out	5Fh, al
		in	al, 0A0h	; PIC 2	 same as 0020 for PIC 1
		test	al, 20h
		jz	short loc_68E
		pop	bp
		retn
sub_683		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_698		proc near
		push	bp
		mov	bp, sp
		cmp	word ptr ds:2950h, 32h
		jge	short loc_6A5
		jmp	loc_7CB
; ---------------------------------------------------------------------------

loc_6A5:
		cmp	word ptr ds:2950h, 5Ah
		jge	short loc_6CD
		cmp	word ptr ds:2950h, 37h
		jnz	short loc_6B6
		jmp	loc_7A6
; ---------------------------------------------------------------------------

loc_6B6:
		cmp	word ptr ds:2950h, 3Ch
		jnz	short loc_6C0
		jmp	loc_7A6
; ---------------------------------------------------------------------------

loc_6C0:
		cmp	word ptr ds:2950h, 41h
		jz	short loc_6CA
		jmp	loc_7AE
; ---------------------------------------------------------------------------

loc_6CA:
		jmp	loc_7A6
; ---------------------------------------------------------------------------

loc_6CD:
		cmp	word ptr ds:2950h, 6Eh
		jge	short loc_720
		push	100h
		push	0C0h
		mov	al, ds:2873h
		cbw
		push	ax
		mov	al, ds:2874h
		cbw
		push	ax
		push	word ptr ds:2876h
		mov	al, ds:2875h
		cbw
		push	ax
		call	sub_1008
		push	140h
		push	0C0h
		mov	al, ds:2873h
		cbw
		inc	ax
		push	ax
		mov	al, ds:2874h
		cbw
		push	ax
		push	word ptr ds:2876h
		mov	al, ds:2875h
		cbw
		push	ax
		call	sub_1008
		dec	byte ptr ds:2874h

loc_711:
		mov	al, ds:2875h
		add	al, 4
		mov	ds:2875h, al
		mov	al, ds:2876h
		add	al, 4
		jmp	short loc_781
; ---------------------------------------------------------------------------

loc_720:
		cmp	word ptr ds:2950h, 82h
		jge	short loc_786
		cmp	word ptr ds:2950h, 6Eh
		jnz	short loc_737
		mov	al, ds:2873h
		add	al, 2
		mov	ds:2873h, al

loc_737:
		push	100h
		push	0C0h
		mov	al, ds:2873h
		cbw
		push	ax
		mov	al, ds:2874h
		cbw
		push	ax
		push	word ptr ds:2876h
		mov	al, ds:2875h
		cbw
		push	ax
		call	sub_1008
		push	140h
		push	0C0h
		mov	al, ds:2873h
		cbw
		inc	ax
		push	ax
		mov	al, ds:2874h
		cbw
		push	ax
		push	word ptr ds:2876h
		mov	al, ds:2875h
		cbw
		push	ax
		call	sub_1008
		inc	byte ptr ds:2874h
		mov	al, ds:2875h
		add	al, 4
		mov	ds:2875h, al
		mov	al, ds:2876h
		add	al, 0FCh

loc_781:
		mov	ds:2876h, al
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_786:
		cmp	word ptr ds:2950h, 0AAh
		jge	short loc_7CB
		cmp	word ptr ds:2950h, 9Bh
		jz	short loc_7A6
		cmp	word ptr ds:2950h, 0A0h
		jz	short loc_7A6
		cmp	word ptr ds:2950h, 0A5h
		jnz	short loc_7AE

loc_7A6:
		mov	al, ds:2873h
		add	al, 2
		mov	ds:2873h, al

loc_7AE:
		push	100h
		push	0C0h
		mov	al, ds:2873h
		cbw
		push	ax
		call	sub_E9C
		push	140h
		push	0C0h
		mov	al, ds:2873h
		cbw
		inc	ax
		push	ax
		call	sub_E9C

loc_7CB:
		pop	bp
		retn
sub_698		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int argc, const char	**argv,	const char **envp)
_main		proc near

_argc		= word ptr  4
_argv		= word ptr  6
_envp		= word ptr  8

		push	bp
		mov	bp, sp
		push	si
		push	di
		xor	ax, ax
		mov	es, ax
		assume es:seg000
		test	byte ptr es:loc_45B+1, 40h
		jz	short loc_7F0
		mov	al, 7
		out	6Ah, al		; PC-98	GDC (6a):
					;
		mov	al, 20h
		out	6Ah, al		; PC-98	GDC (6a):
					;
		mov	al, 6
		out	6Ah, al		; PC-98	GDC (6a):
					;
		and	byte ptr es:[54Dh], 7Fh

loc_7F0:
		call	sub_384
		call	sub_439

loc_7F6:
		cmp	word ptr ds:2950h, 0B4h
		jle	short loc_80C
		cmp	byte ptr ds:2872h, 0
		jle	short loc_873
		mov	al, ds:2872h
		add	al, 0FEh
		jmp	short loc_818
; ---------------------------------------------------------------------------

loc_80C:
		cmp	byte ptr ds:2872h, 64h
		jge	short loc_822
		mov	al, ds:2872h
		add	al, 2

loc_818:
		mov	ds:2872h, al
		cbw
		mov	PaletteTone, ax
		call	palette_show

loc_822:
		push	0C0h
		push	0
		call	grcg_setcolor
		push	0Ch
		push	64h
		push	43h
		push	12Bh
		call	grcg_byteboxfill_x
		call	sub_5B6
		call	sub_502
		call	sub_698
		call	sub_683
		call	sub_683
		mov	al, ds:2870h
		mov	ds:2871h, al
		out	0A4h, al	; Interrupt Controller #2, 8259A
		xor	byte ptr ds:2870h, 1
		mov	al, ds:2870h
		out	0A6h, al	; Interrupt Controller #2, 8259A
		xor	di, di
		xor	si, si
		jmp	short loc_864
; ---------------------------------------------------------------------------

loc_85D:
		push	si
		call	sub_ACE
		or	di, ax
		inc	si

loc_864:
		cmp	si, 8
		jl	short loc_85D
		or	di, di
		jnz	short loc_873
		inc	word ptr ds:2950h
		jmp	short loc_7F6
; ---------------------------------------------------------------------------

loc_873:
		call	sub_3D0
		pop	di
		pop	si
		pop	bp
		retn
_main		endp

include libs/BorlandC/text_clear.asm
include libs/BorlandC/txesc.asm
		db    0

; =============== S U B	R O U T	I N E =======================================


sub_8DA		proc near
		mov	ah, 42h
		mov	ch, 0C0h
		int	18h		; TRANSFER TO ROM BASIC
					; causes transfer to ROM-based BASIC (IBM-PC)
					; often	reboots	a compatible; often has	no effect at all
		mov	ax, 0A800h
		mov	graph_VramSeg, ax
		mov	ClipYT_seg, ax
		mov	graph_VramWords, 3E80h
		xor	ax, ax
		mov	ClipXL, ax
		mov	ClipYT, ax
		mov	es, ax
		mov	ah, byte ptr es:[54Dh]
		and	ah, 4
		add	ah, 3Fh
		and	ah, 40h
		mov	graph_VramZoom, ax
		mov	ax, 27Fh
		mov	ClipXR, ax
		mov	ClipXW, ax
		mov	ax, 190h
		mov	graph_VramLines, ax
		dec	ax
		mov	ClipYB, ax
		mov	ClipYH, ax
		mov	ClipYB_adr, 7CB0h
		retn
sub_8DA		endp

include libs/master.lib/graph_clear.asm

; =============== S U B	R O U T	I N E =======================================


sub_94C		proc near
		mov	ah, 41h
		int	18h		; TRANSFER TO ROM BASIC
					; causes transfer to ROM-based BASIC (IBM-PC)
					; often	reboots	a compatible; often has	no effect at all
		retn
sub_94C		endp

include libs/master.lib/graph_show.asm

; =============== S U B	R O U T	I N E =======================================


sub_958		proc near
		mov	al, 41h
		out	6Ah, al		; PC-98	GDC (6a):
					; Set display mode to LCD
		mov	PaletteTone, 0
		call	palette_show
		mov	al, 0
		out	0A4h, al	; Interrupt Controller #2, 8259A
		out	0A6h, al	; Interrupt Controller #2, 8259A
		call	graph_show
		call	sub_8DA
		call	graph_clear
		call	palette_init
		retn
sub_958		endp

include libs/master.lib/palette_show.asm
include libs/master.lib/palette_init.asm
include libs/master.lib/keybeep.asm

; =============== S U B	R O U T	I N E =======================================


sub_ACE		proc near
		mov	bx, sp
		mov	ax, ss:[bx+2]
		mov	ah, 4
		int	18h		; TRANSFER TO ROM BASIC
					; causes transfer to ROM-based BASIC (IBM-PC)
					; often	reboots	a compatible; often has	no effect at all
		mov	al, ah
		mov	ah, 0
		retn	2
sub_ACE		endp

include libs/master.lib/bfnt_header_read.asm
include libs/master.lib/bfnt_entry_pat.asm
include libs/master.lib/bfnt_header_analysis.asm
include libs/master.lib/bfnt_palette_set.asm
include libs/master.lib/dos_close.asm
include libs/master.lib/dos_ropen.asm
include libs/master.lib/super_entry_bfnt.asm
include libs/master.lib/super_cancel_pat.asm
include libs/master.lib/super_entry_pat.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_E9C		proc near

arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		push	bp
		mov	bp, sp
		push	ds
		push	si
		push	di
		mov	cx, [bp+arg_4]
		mov	ax, [bp+arg_2]
		mov	bx, [bp+arg_0]
		mov	bp, ax
		shl	ax, 2
		add	bp, ax
		shl	bp, 4
		shr	cx, 3
		add	bp, cx
		shl	bx, 1
		mov	ax, [bx+2DC6h]
		xor	si, si
		mov	ds, word ptr [bx+29C6h]
		mov	bl, ah
		xor	bh, bh
		mov	dx, 50h
		sub	dl, ah
		mov	ah, al
		mov	cx, 0A800h
		mov	es, cx
		assume es:nothing
		mov	al, 0C0h
		out	7Ch, al
		mov	al, 0
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		call	sub_F18
		mov	al, 0CEh
		out	7Ch, al
		mov	al, 0FFh
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		call	sub_F18
		mov	al, 0CDh
		out	7Ch, al
		call	sub_F18
		mov	al, 0CBh
		out	7Ch, al
		call	sub_F18
		mov	al, 0C7h
		out	7Ch, al
		call	sub_F18
		xor	al, al
		out	7Ch, al
		pop	di
		pop	si
		pop	ds
		pop	bp
		retn	6
sub_E9C		endp


; =============== S U B	R O U T	I N E =======================================


sub_F18		proc near
		mov	di, bp
		mov	al, ah
		test	di, 1
		jnz	short loc_F44
		shr	bx, 1
		jb	short loc_F34

loc_F26:
		mov	cx, bx
		rep movsw
		add	di, dx
		dec	al
		jnz	short loc_F26
		shl	bx, 1
		retn
; ---------------------------------------------------------------------------
		nop

loc_F34:
		mov	cx, bx
		rep movsw
		movsb
		add	di, dx
		dec	al
		jnz	short loc_F34
		stc
		rcl	bx, 1
		retn
; ---------------------------------------------------------------------------
		nop

loc_F44:
		shr	bx, 1
		jb	short loc_F58

loc_F48:
		mov	cx, bx
		dec	cx
		movsb
		rep movsw
		movsb
		add	di, dx
		dec	al
		jnz	short loc_F48
		shl	bx, 1
		retn
; ---------------------------------------------------------------------------

loc_F58:
		mov	cx, bx
		movsb
		rep movsw
		add	di, dx
		dec	al
		jnz	short loc_F58
		stc
		rcl	bx, 1
		retn
sub_F18		endp

include libs/master.lib/super_free.asm
include libs/master.lib/super_entry_at.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_1008	proc near

var_2		= byte ptr -2
arg_0		= word ptr  4
arg_2		= byte ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah
arg_8		= word ptr  0Ch
arg_A		= word ptr  0Eh

		enter	2, 0
		push	ds
		push	si
		push	di
		push	bp
		mov	bx, [bp+arg_6]
		add	bx, bx
		mov	cx, [bx+2DC6h]
		inc	ch
		mov	ds:3346h, ch
		mov	byte ptr cs:sub_10E0+5,	cl
		push	word ptr [bx+29C6h]
		imul	di, [bp+arg_8],	50h
		mov	ax, 0FFFFh
		and	ax, [bp+arg_4]
		mov	[bp+var_2], ah
		jns	short loc_103A
		neg	[bp+arg_4]

loc_103A:
		xor	ch, ch
		xor	si, si

loc_103E:
		mov	ax, si
		cwd
		shl	ax, 7
		div	[bp+arg_4]
		add	ax, [bp+arg_0]
		mov	bx, 2568h
		xlat
		imul	[bp+arg_2]
		sar	ax, 7
		add	ax, [bp+arg_A]
		mov	dx, ax
		and	al, 0Fh
		xor	dl, al
		sar	dx, 3
		add	dx, di
		mov	ah, ds:3346h
		test	ah, 1
		jnz	short loc_106D
		xor	al, 8

loc_106D:
		mov	[si+31C6h], dx
		mov	[si+3246h], ax
		xor	bh, bh
		mov	bl, al
		add	bx, bx
		mov	dx, [bx+22C6h]
		mov	[si+32C6h], dx
		test	[bp+var_2], 0FFh
		jz	short loc_108C
		neg	[bp+arg_2]

loc_108C:
		add	di, 50h
		add	si, 2
		loop	loc_103E
		pop	ds
		xor	si, si
		mov	ax, 0A800h
		mov	es, ax
		assume es:nothing
		cld
		mov	al, 0C0h
		out	7Ch, al
		xor	al, al
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		call	sub_10E0
		mov	al, 0CEh
		out	7Ch, al
		mov	al, 0FFh
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		out	7Eh, al
		call	sub_10E0
		mov	al, 0CDh
		out	7Ch, al
		call	sub_10E0
		mov	al, 0CBh
		out	7Ch, al
		call	sub_10E0
		mov	al, 0C7h
		out	7Ch, al
		call	sub_10E0
		xor	al, al
		out	7Ch, al
		pop	bp
		pop	di
		pop	si
		pop	ds
		leave
		retn	0Ch
sub_1008	endp


; =============== S U B	R O U T	I N E =======================================


sub_10E0	proc near
		mov	byte ptr ss:3346h, 0
		xor	bp, bp

loc_10E8:
		xor	dx, dx
		mov	di, [bp+31C6h]
		mov	cx, [bp+3246h]
		mov	bx, [bp+32C6h]
		shr	ch, 1
		jb	short loc_1108
		lodsb
		shl	ax, 8
		test	cl, 8
		jz	short loc_1109
		ror	ax, cl
		jmp	short loc_1112
; ---------------------------------------------------------------------------
		nop

loc_1108:
		lodsw

loc_1109:
		ror	ax, cl
		xor	dx, ax
		and	ax, bx
		xor	ax, dx
		stosw

loc_1112:
		xor	dx, ax
		dec	ch
		jnz	short loc_1108
		mov	es:[di], dx
		add	bp, 2
		dec	byte ptr ss:3346h
		jnz	short loc_10E8
		retn
sub_10E0	endp

include libs/master.lib/smem_wget.asm
include libs/master.lib/smem_release.asm
include libs/master.lib/memheap.asm
include libs/master.lib/mem_assign.asm

; =============== S U B	R O U T	I N E =======================================


sub_136A	proc near
		cmp	mem_TopSeg, 0
		jz	short loc_1394
		mov	ax, ds:3348h
		cmp	ds:334Ah, ax
		jnz	short loc_1398
		mov	ax, mem_TopSeg
		cmp	ds:334Eh, ax
		jnz	short loc_1398
		mov	es, ax
		xor	ax, ax
		cmp	mem_MyOwn, ax
		mov	mem_TopSeg, ax
		jz	short loc_1394
		mov	ah, 49h
		int	21h		; DOS -	2+ - FREE MEMORY
					; ES = segment address of area to be freed

loc_1394:
		mov	ax, 1
		retn
; ---------------------------------------------------------------------------

loc_1398:
		xor	ax, ax
		stc
		retn
sub_136A	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_139C	proc near

arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah

		push	bp
		mov	bp, sp
		mov	ax, [bp+arg_6]
		mov	bx, [bp+arg_2]
		test	ax, bx
		js	short loc_1428
		cmp	ax, bx
		jl	short loc_13AE
		xchg	ax, bx

loc_13AE:
		cmp	ax, 8000h
		sbb	dx, dx
		and	ax, dx
		mov	cx, graph_VramWidth
		shl	cx, 3
		dec	cx
		sub	bx, cx
		sbb	dx, dx
		and	bx, dx
		add	bx, cx
		sub	bx, ax
		jl	short loc_1428
		mov	ClipXL, ax
		mov	ClipXW, bx
		add	ax, bx
		mov	ClipXR, ax
		mov	ax, [bp+arg_4]
		mov	bx, [bp+arg_0]
		test	ax, bx
		js	short loc_1428
		cmp	ax, bx
		jl	short loc_13E4
		xchg	ax, bx

loc_13E4:
		cmp	ax, 8000h
		sbb	dx, dx
		and	ax, dx
		mov	cx, graph_VramLines
		dec	cx
		sub	bx, cx
		sbb	dx, dx
		and	bx, dx
		add	bx, cx
		sub	bx, ax
		jl	short loc_1428
		mov	ClipYT, ax
		mov	cx, ax
		mov	ClipYH, bx
		add	ax, bx
		mov	ClipYB, ax
		mov	ax, graph_VramWidth
		xchg	ax, bx
		mul	bx
		mov	ClipYB_adr, ax
		mov	ax, bx
		shr	ax, 4
		mul	cx
		add	ax, graph_VramSeg
		mov	ClipYT_seg, ax
		mov	ax, 1
		pop	bp
		retn	8
; ---------------------------------------------------------------------------

loc_1428:
		xor	ax, ax
		pop	bp
		retn	8
sub_139C	endp

include libs/master.lib/grcg_hline.asm
include libs/master.lib/grcg_setcolor.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_14E4	proc near

arg_0		= word ptr  2
arg_2		= word ptr  4

		mov	bx, bp
		mov	bp, sp
		mov	cx, [bp+arg_2]
		mov	dx, [bp+arg_0]
		mov	bp, bx
		cmp	cx, ClipXL
		jl	short locret_1524
		cmp	cx, ClipXR
		jg	short locret_1524
		sub	dx, ClipYT
		jl	short locret_1524
		cmp	dx, ClipYH
		jg	short locret_1524
		mov	ax, dx
		shl	ax, 2
		add	dx, ax
		add	dx, ClipYT_seg
		mov	es, dx
		mov	bx, cx
		shr	bx, 3
		and	cl, 7
		mov	al, 80h
		shr	al, cl
		mov	es:[bx], al

locret_1524:
		retn	4
sub_14E4	endp

include libs/master.lib/egc.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_1588	proc near

var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	ax, [bp+arg_0]
		test	ax, ax
		jz	short loc_160A
		mov	si, ax
		mov	[bp+var_2], ax
		mov	di, 0

loc_159D:
		mov	bx, [bp+arg_4]
		mov	ax, bx
		sub	ax, si
		push	ax
		add	bx, si
		push	bx
		mov	ax, [bp+arg_2]
		sub	ax, di
		push	ax
		call	grcg_hline
		mov	bx, [bp+arg_4]
		mov	ax, bx
		sub	ax, si
		push	ax
		add	bx, si
		push	bx
		mov	ax, [bp+arg_2]
		add	ax, di
		push	ax
		call	grcg_hline
		mov	ax, di
		stc
		rcl	ax, 1
		sub	[bp+var_2], ax
		jns	short loc_15FF
		mov	bx, [bp+arg_4]
		mov	ax, bx
		sub	ax, di
		push	ax
		add	bx, di
		push	bx
		mov	ax, [bp+arg_2]
		sub	ax, si
		push	ax
		call	grcg_hline
		mov	bx, [bp+arg_4]
		mov	ax, bx
		sub	ax, di
		push	ax
		add	bx, di
		push	bx
		mov	ax, [bp+arg_2]
		add	ax, si
		push	ax
		call	grcg_hline
		dec	si
		mov	ax, si
		shl	ax, 1
		add	[bp+var_2], ax

loc_15FF:
		inc	di
		cmp	si, di
		jnb	short loc_159D
		pop	di
		pop	si
		leave
		retn	6
; ---------------------------------------------------------------------------

loc_160A:
		push	[bp+arg_4]
		push	[bp+arg_2]
		call	sub_14E4
		pop	di
		pop	si
		leave
		retn	6
sub_1588	endp

include libs/master.lib/grcg_byteboxfill_x.asm

; =============== S U B	R O U T	I N E =======================================


sub_16B2	proc near
		mov	ax, 4E35h
		mul	word_266A
		mov	cx, ax
		mov	ax, 15Ah
		mul	word_2668
		add	cx, ax
		mov	ax, 4E35h
		mul	word_2668
		add	ax, 1
		adc	dx, cx
		mov	word_2668, ax
		mov	ax, dx
		mov	word_266A, ax
		and	ah, 7Fh
		retn
sub_16B2	endp

include libs/BorlandC/__abort.asm
include libs/BorlandC/atexit.asm
include libs/BorlandC/errormsg.asm
include libs/BorlandC/exit.asm
include libs/BorlandC/H_LRSH.ASM
include libs/BorlandC/__IOERROR.ASM
include libs/BorlandC/_isatty.asm
include libs/BorlandC/lseek.asm
include libs/BorlandC/N_LXMUL.ASM
include libs/BorlandC/setupio.asm
include libs/BorlandC/brk.asm
include libs/BorlandC/nearheap.asm
include libs/BorlandC/fflush.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

; int flushall(void)
_flushall	proc near

var_6		= word ptr -6
var_4		= word ptr -4
stream		= word ptr -2

		push	bp
		mov	bp, sp
		sub	sp, 6
		push	si
		push	di
		mov	[bp+var_6], 0
		mov	ax, __nfile
		mov	[bp+var_4], ax
		mov	[bp+stream], 2694h
		jmp	short loc_1CF4
; ---------------------------------------------------------------------------

loc_1CDF:
		mov	bx, [bp+stream]
		test	byte ptr [bx+2], 3
		jz	short loc_1CF0
		push	bx		; stream
		call	_fflush
		pop	cx
		inc	[bp+var_6]

loc_1CF0:
		add	[bp+stream], 10h

loc_1CF4:
		mov	ax, [bp+var_4]
		dec	[bp+var_4]
		or	ax, ax
		jnz	short loc_1CDF
		mov	ax, [bp+var_6]
		pop	di
		pop	si
		mov	sp, bp
		pop	bp
		retn
_flushall	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

sub_1D07	proc near

var_2		= word ptr -2
arg_0		= word ptr  4

		push	bp
		mov	bp, sp
		sub	sp, 2
		push	si
		push	di
		mov	bx, [bp+arg_0]
		cmp	word ptr [bx], 0
		jge	short loc_1D21
		mov	dx, [bx+6]
		add	dx, [bx]
		inc	dx
		mov	ax, dx
		jmp	short loc_1D2D
; ---------------------------------------------------------------------------

loc_1D21:
		mov	bx, [bp+arg_0]
		mov	ax, [bx]
		cwd
		xor	ax, dx
		sub	ax, dx
		mov	dx, ax

loc_1D2D:
		mov	[bp+var_2], ax
		mov	bx, [bp+arg_0]
		test	byte ptr [bx+2], 40h
		jnz	short loc_1D6C
		mov	bx, [bp+arg_0]
		mov	cx, [bx+0Ah]
		cmp	word ptr [bx], 0
		jge	short loc_1D65
		jmp	short loc_1D51
; ---------------------------------------------------------------------------

loc_1D46:
		dec	cx
		mov	bx, cx
		cmp	byte ptr [bx], 0Ah
		jnz	short loc_1D51
		inc	[bp+var_2]

loc_1D51:
		mov	ax, dx
		dec	dx
		or	ax, ax
		jnz	short loc_1D46
		jmp	short loc_1D6C
; ---------------------------------------------------------------------------

loc_1D5A:
		mov	bx, cx
		inc	cx
		cmp	byte ptr [bx], 0Ah
		jnz	short loc_1D65
		inc	[bp+var_2]

loc_1D65:
		mov	ax, dx
		dec	dx
		or	ax, ax
		jnz	short loc_1D5A

loc_1D6C:
		mov	ax, [bp+var_2]
		pop	di
		pop	si
		mov	sp, bp
		pop	bp
		retn	2
sub_1D07	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

; int __cdecl fseek(FILE *stream, __int32 offset, int whence)
_fseek		proc near

stream		= word ptr  4
_offset		= dword	ptr  6
whence		= word ptr  0Ah

		push	bp
		mov	bp, sp
		push	si
		push	di
		push	[bp+stream]	; stream
		call	_fflush
		pop	cx
		or	ax, ax
		jz	short loc_1D8C
		mov	ax, 0FFFFh
		jmp	short loc_1DDC
; ---------------------------------------------------------------------------

loc_1D8C:
		cmp	[bp+whence], 1
		jnz	short loc_1DA5
		mov	bx, [bp+stream]
		cmp	word ptr [bx], 0
		jle	short loc_1DA5
		push	bx
		call	sub_1D07
		cwd
		sub	word ptr [bp+_offset], ax
		sbb	word ptr [bp+_offset+2],	dx

loc_1DA5:
		mov	bx, [bp+stream]
		and	word ptr [bx+2], 0FE5Fh
		mov	word ptr [bx], 0
		mov	ax, [bx+8]
		mov	[bx+0Ah], ax
		push	[bp+whence]	; fromwhere
		push	word ptr [bp+_offset+2]
		push	word ptr [bp+_offset] ; offset
		mov	al, [bx+4]
		cbw
		push	ax		; handle
		call	_lseek
		add	sp, 8
		cmp	dx, 0FFFFh
		jnz	short loc_1DDA
		cmp	ax, 0FFFFh
		jnz	short loc_1DDA
		mov	ax, 0FFFFh
		jmp	short loc_1DDC
; ---------------------------------------------------------------------------

loc_1DDA:
		xor	ax, ax

loc_1DDC:
		pop	di
		pop	si
		pop	bp
		retn
_fseek		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

; __int32 __cdecl ftell(FILE *stream)
_ftell		proc near

var_8		= word ptr -8
var_6		= word ptr -6
_offset		= dword	ptr -4
stream		= word ptr  4

		push	bp
		mov	bp, sp
		sub	sp, 8
		push	si
		push	di
		mov	ax, 1
		push	ax		; fromwhere
		xor	ax, ax
		push	ax
		push	ax		; offset
		mov	bx, [bp+stream]
		mov	al, [bx+4]
		cbw
		push	ax		; handle
		call	_lseek
		add	sp, 8
		mov	word ptr [bp+_offset+2],	dx
		mov	word ptr [bp+_offset], ax
		cmp	dx, 0FFFFh
		jnz	short loc_1E11
		cmp	ax, 0FFFFh
		jnz	short loc_1E11
		jmp	loc_1EA1
; ---------------------------------------------------------------------------

loc_1E11:
		mov	bx, [bp+stream]
		cmp	word ptr [bx], 0
		jge	short loc_1E94
		mov	al, [bx+4]
		cbw
		add	ax, ax
		mov	bx, ax
		test	byte ptr [bx+27D7h], 8
		jz	short loc_1E85
		mov	ax, 2
		push	ax		; fromwhere
		xor	ax, ax
		push	ax
		push	ax		; offset
		mov	bx, [bp+stream]
		mov	al, [bx+4]
		cbw
		push	ax		; handle
		call	_lseek
		add	sp, 8
		mov	[bp+var_6], dx
		mov	[bp+var_8], ax
		cmp	dx, 0FFFFh
		jnz	short loc_1E50
		cmp	ax, 0FFFFh
		jnz	short loc_1E50
		jmp	short loc_1EA7
; ---------------------------------------------------------------------------

loc_1E50:
		xor	ax, ax
		push	ax		; fromwhere
		push	word ptr [bp+_offset+2]
		push	word ptr [bp+_offset] ; offset
		mov	bx, [bp+stream]
		mov	al, [bx+4]
		cbw
		push	ax		; handle
		call	_lseek
		add	sp, 8
		cmp	dx, 0FFFFh
		jnz	short loc_1E79
		cmp	ax, 0FFFFh
		jnz	short loc_1E79
		mov	dx, 0FFFFh
		mov	ax, 0FFFFh
		jmp	short loc_1EA7
; ---------------------------------------------------------------------------

loc_1E79:
		mov	dx, [bp+var_6]
		mov	ax, [bp+var_8]
		mov	word ptr [bp+_offset+2],	dx
		mov	word ptr [bp+_offset], ax

loc_1E85:
		push	[bp+stream]
		call	sub_1D07
		cwd
		add	word ptr [bp+_offset], ax
		adc	word ptr [bp+_offset+2],	dx
		jmp	short loc_1EA1
; ---------------------------------------------------------------------------

loc_1E94:
		push	[bp+stream]
		call	sub_1D07
		cwd
		sub	word ptr [bp+_offset], ax
		sbb	word ptr [bp+_offset+2],	dx

loc_1EA1:
		mov	dx, word ptr [bp+_offset+2]
		mov	ax, word ptr [bp+_offset]

loc_1EA7:
		pop	di
		pop	si
		mov	sp, bp
		pop	bp
		retn
_ftell		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

; int __cdecl setvbuf(FILE *stream, char *buf, int type, size_t	size)
_setvbuf	proc near

stream		= word ptr  4
buf		= word ptr  6
_type		= word ptr  8
_size		= word ptr  0Ah

		push	bp
		mov	bp, sp
		push	si
		push	di
		mov	bx, [bp+stream]
		mov	ax, [bx+0Eh]
		cmp	ax, [bp+stream]
		jz	short loc_1EC0
		jmp	loc_1F6B
; ---------------------------------------------------------------------------

loc_1EC0:
		cmp	[bp+_type], 2
		jle	short loc_1EC9
		jmp	loc_1F6B
; ---------------------------------------------------------------------------

loc_1EC9:
		cmp	[bp+_size], 7FFFh
		jbe	short loc_1ED3
		jmp	loc_1F6B
; ---------------------------------------------------------------------------

loc_1ED3:
		cmp	word_2866, 0
		jnz	short loc_1EE9
		cmp	[bp+stream], 26A4h
		jnz	short loc_1EE9
		mov	word_2866, 1
		jmp	short loc_1EFD
; ---------------------------------------------------------------------------

loc_1EE9:
		cmp	word_2864, 0
		jnz	short loc_1EFD
		cmp	[bp+stream], 2694h
		jnz	short loc_1EFD
		mov	word_2864, 1

loc_1EFD:
		mov	bx, [bp+stream]
		cmp	word ptr [bx], 0
		jz	short loc_1F14
		mov	ax, 1
		push	ax		; whence
		xor	ax, ax
		push	ax
		push	ax		; offset
		push	bx		; stream
		call	_fseek
		add	sp, 8

loc_1F14:
		mov	bx, [bp+stream]
		test	byte ptr [bx+2], 4
		jz	short loc_1F24
		push	word ptr [bx+8]	; block
		call	_free
		pop	cx

loc_1F24:
		mov	bx, [bp+stream]
		and	word ptr [bx+2], 0FFF3h
		mov	word ptr [bx+6], 0
		mov	ax, [bp+stream]
		add	ax, 5
		mov	[bx+8],	ax
		mov	[bx+0Ah], ax
		cmp	[bp+_type], 2
		jz	short loc_1F8C
		cmp	[bp+_size], 0
		jbe	short loc_1F8C
		mov	_exitbuf, 2128h
		cmp	[bp+buf], 0
		jnz	short loc_1F70
		push	[bp+_size]	; size
		call	_malloc
		pop	cx
		mov	[bp+buf], ax
		or	ax, ax
		jz	short loc_1F6B
		mov	bx, [bp+stream]
		or	word ptr [bx+2], 4
		jmp	short loc_1F70
; ---------------------------------------------------------------------------

loc_1F6B:
		mov	ax, 0FFFFh
		jmp	short loc_1F8E
; ---------------------------------------------------------------------------

loc_1F70:
		mov	bx, [bp+stream]
		mov	ax, [bp+buf]
		mov	[bx+0Ah], ax
		mov	[bx+8],	ax
		mov	ax, [bp+_size]
		mov	[bx+6],	ax
		cmp	[bp+_type], 1
		jnz	short loc_1F8C
		or	word ptr [bx+2], 8

loc_1F8C:
		xor	ax, ax

loc_1F8E:
		pop	di
		pop	si
		pop	bp
		retn
_setvbuf	endp

include libs/BorlandC/_strlen.asm
include libs/BorlandC/write.asm
include libs/BorlandC/writea.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: library function bp-based	frame

__xfflush	proc near

var_4		= word ptr -4
stream		= word ptr -2

		push	bp
		mov	bp, sp
		sub	sp, 4
		push	si
		push	di
		mov	[bp+var_4], 4
		mov	[bp+stream], 2694h
		jmp	short loc_2151
; ---------------------------------------------------------------------------

loc_213C:
		mov	bx, [bp+stream]
		test	byte ptr [bx+2], 3
		jz	short loc_214A
		push	bx		; stream
		call	_fflush
		pop	cx

loc_214A:
		dec	[bp+var_4]
		add	[bp+stream], 10h

loc_2151:
		cmp	[bp+var_4], 0
		jnz	short loc_213C
		pop	di
		pop	si
		mov	sp, bp
		pop	bp
		retn
__xfflush	endp

; ---------------------------------------------------------------------------
		db 0
		db    0
		db    0
include libs/BorlandC/c0[data].asm
aTouhou_dat	db 'touhou.dat',0
		db 4, 3, 2, 1, 0
aMasters_libVer	db 'MASTERS.LIB Version 0.23 Copyright (c)1995 A.Koizuka,Kazumi,steel'
		db 'man,iR,All rights reserved.',0
		db 0
include libs/master.lib/grp[data].asm
		db 0
include libs/master.lib/pal[data].asm
include libs/master.lib/bfnt_id[data].asm
include libs/master.lib/dos_ropen[data].asm
include libs/master.lib/super_entry_bfnt[data].asm
include libs/master.lib/superpa[data].asm
include libs/master.lib/mem[data].asm
include libs/master.lib/clip[data].asm
include libs/master.lib/edges[data].asm
		db    0
		db    0
		db    6
		db    0
		db  0Dh
		db    0
		db  13h
		db    0
		db  19h
		db    0
		db  1Fh
		db    0
		db  26h	; &
		db    0
		db  2Ch	; ,
		db    0
		db  32h	; 2
		db    0
		db  38h	; 8
		db    0
		db  3Eh	; >
		db    0
		db  44h	; D
		db    0
		db  4Ah	; J
		db    0
		db  50h	; P
		db    0
		db  56h	; V
		db    0
		db  5Ch	; \
		db    0
		db  62h	; b
		db    0
		db  68h	; h
		db    0
		db  6Dh	; m
		db    0
		db  73h	; s
		db    0
		db  79h	; y
		db    0
		db  7Eh	; ~
		db    0
		db  84h	; Ñ
		db    0
		db  89h	; â
		db    0
		db  8Eh	; é
		db    0
		db  93h	; ì
		db    0
		db  98h	; ò
		db    0
		db  9Dh	; ù
		db    0
		db 0A2h	; ¢
		db    0
		db 0A7h	; ß
		db    0
		db 0ACh	; ¨
		db    0
		db 0B1h	; ±
		db    0
		db 0B5h	; µ
		db    0
		db 0B9h	; π
		db    0
		db 0BEh	; æ
		db    0
		db 0C2h	; ¬
		db    0
		db 0C6h	; ∆
		db    0
		db 0CAh	;  
		db    0
		db 0CEh	; Œ
		db    0
		db 0D1h	; —
		db    0
		db 0D5h	; ’
		db    0
		db 0D8h	; ÿ
		db    0
		db 0DCh	; ‹
		db    0
		db 0DFh	; ﬂ
		db    0
		db 0E2h	; ‚
		db    0
		db 0E5h	; Â
		db    0
		db 0E7h	; Á
		db    0
		db 0EAh	; Í
		db    0
		db 0EDh	; Ì
		db    0
		db 0EFh	; Ô
		db    0
		db 0F1h	; Ò
		db    0
		db 0F3h	; Û
		db    0
		db 0F5h	; ı
		db    0
		db 0F7h	; ˜
		db    0
		db 0F8h	; ¯
		db    0
		db 0FAh	; ˙
		db    0
		db 0FBh	; ˚
		db    0
		db 0FCh	; ¸
		db    0
		db 0FDh	; ˝
		db    0
		db 0FEh	; ˛
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FEh	; ˛
		db    0
		db 0FDh	; ˝
		db    0
		db 0FCh	; ¸
		db    0
		db 0FBh	; ˚
		db    0
		db 0FAh	; ˙
		db    0
		db 0F8h	; ¯
		db    0
		db 0F7h	; ˜
		db    0
		db 0F5h	; ı
		db    0
		db 0F3h	; Û
		db    0
		db 0F1h	; Ò
		db    0
		db 0EFh	; Ô
		db    0
		db 0EDh	; Ì
		db    0
		db 0EAh	; Í
		db    0
		db 0E7h	; Á
		db    0
		db 0E5h	; Â
		db    0
		db 0E2h	; ‚
		db    0
		db 0DFh	; ﬂ
		db    0
		db 0DCh	; ‹
		db    0
		db 0D8h	; ÿ
		db    0
		db 0D5h	; ’
		db    0
		db 0D1h	; —
		db    0
		db 0CEh	; Œ
		db    0
		db 0CAh	;  
		db    0
		db 0C6h	; ∆
		db    0
		db 0C2h	; ¬
		db    0
		db 0BEh	; æ
		db    0
		db 0B9h	; π
		db    0
		db 0B5h	; µ
		db    0
		db 0B1h	; ±
		db    0
		db 0ACh	; ¨
		db    0
		db 0A7h	; ß
		db    0
		db 0A2h	; ¢
		db    0
		db  9Dh	; ù
		db    0
		db  98h	; ò
		db    0
		db  93h	; ì
		db    0
		db  8Eh	; é
		db    0
		db  89h	; â
		db    0
		db  84h	; Ñ
		db    0
		db  7Eh	; ~
		db    0
		db  79h	; y
		db    0
		db  73h	; s
		db    0
		db  6Dh	; m
		db    0
		db  68h	; h
		db    0
		db  62h	; b
		db    0
		db  5Ch	; \
		db    0
		db  56h	; V
		db    0
		db  50h	; P
		db    0
		db  4Ah	; J
		db    0
		db  44h	; D
		db    0
		db  3Eh	; >
		db    0
		db  38h	; 8
		db    0
		db  32h	; 2
		db    0
		db  2Ch	; ,
		db    0
		db  26h	; &
		db    0
		db  1Fh
		db    0
		db  19h
		db    0
		db  13h
		db    0
		db  0Dh
		db    0
		db    6
		db    0
		db    0
		db    0
		db 0FAh	; ˙
		db 0FFh
		db 0F3h	; Û
		db 0FFh
		db 0EDh	; Ì
		db 0FFh
		db 0E7h	; Á
		db 0FFh
		db 0E1h	; ·
		db 0FFh
		db 0DAh	; ⁄
		db 0FFh
		db 0D4h	; ‘
		db 0FFh
		db 0CEh	; Œ
		db 0FFh
		db 0C8h	; »
		db 0FFh
		db 0C2h	; ¬
		db 0FFh
		db 0BCh	; º
		db 0FFh
		db 0B6h	; ∂
		db 0FFh
		db 0B0h	; ∞
		db 0FFh
		db 0AAh	; ™
		db 0FFh
		db 0A4h	; §
		db 0FFh
		db  9Eh	; û
		db 0FFh
		db  98h	; ò
		db 0FFh
		db  93h	; ì
		db 0FFh
		db  8Dh	; ç
		db 0FFh
		db  87h	; á
		db 0FFh
		db  82h	; Ç
		db 0FFh
		db  7Ch	; |
		db 0FFh
		db  77h	; w
		db 0FFh
		db  72h	; r
		db 0FFh
		db  6Dh	; m
		db 0FFh
		db  68h	; h
		db 0FFh
		db  63h	; c
		db 0FFh
		db  5Eh	; ^
		db 0FFh
		db  59h	; Y
		db 0FFh
		db  54h	; T
		db 0FFh
		db  4Fh	; O
		db 0FFh
		db  4Bh	; K
		db 0FFh
		db  47h	; G
		db 0FFh
		db  42h	; B
		db 0FFh
		db  3Eh	; >
		db 0FFh
		db  3Ah	; :
		db 0FFh
		db  36h	; 6
		db 0FFh
		db  32h	; 2
		db 0FFh
		db  2Fh	; /
		db 0FFh
		db  2Bh	; +
		db 0FFh
		db  28h	; (
		db 0FFh
		db  24h	; $
		db 0FFh
		db  21h	; !
		db 0FFh
		db  1Eh
		db 0FFh
		db  1Bh
		db 0FFh
		db  19h
		db 0FFh
		db  16h
		db 0FFh
		db  13h
		db 0FFh
		db  11h
		db 0FFh
		db  0Fh
		db 0FFh
		db  0Dh
		db 0FFh
		db  0Bh
		db 0FFh
		db    9
		db 0FFh
		db    8
		db 0FFh
		db    6
		db 0FFh
		db    5
		db 0FFh
		db    4
		db 0FFh
		db    3
		db 0FFh
		db    2
		db 0FFh
		db    1
		db 0FFh
		db    1
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    1
		db 0FFh
		db    1
		db 0FFh
		db    2
		db 0FFh
		db    3
		db 0FFh
		db    4
		db 0FFh
		db    5
		db 0FFh
		db    6
		db 0FFh
		db    8
		db 0FFh
		db    9
		db 0FFh
		db  0Bh
		db 0FFh
		db  0Dh
		db 0FFh
		db  0Fh
		db 0FFh
		db  11h
		db 0FFh
		db  13h
		db 0FFh
		db  16h
		db 0FFh
		db  19h
		db 0FFh
		db  1Bh
		db 0FFh
		db  1Eh
		db 0FFh
		db  21h	; !
		db 0FFh
		db  24h	; $
		db 0FFh
		db  28h	; (
		db 0FFh
		db  2Bh	; +
		db 0FFh
		db  2Fh	; /
		db 0FFh
		db  32h	; 2
		db 0FFh
		db  36h	; 6
		db 0FFh
		db  3Ah	; :
		db 0FFh
		db  3Eh	; >
		db 0FFh
		db  42h	; B
		db 0FFh
		db  47h	; G
		db 0FFh
		db  4Bh	; K
		db 0FFh
		db  4Fh	; O
		db 0FFh
		db  54h	; T
		db 0FFh
		db  59h	; Y
		db 0FFh
		db  5Eh	; ^
		db 0FFh
		db  63h	; c
		db 0FFh
		db  68h	; h
		db 0FFh
		db  6Dh	; m
		db 0FFh
		db  72h	; r
		db 0FFh
		db  77h	; w
		db 0FFh
		db  7Ch	; |
		db 0FFh
		db  82h	; Ç
		db 0FFh
		db  87h	; á
		db 0FFh
		db  8Dh	; ç
		db 0FFh
		db  93h	; ì
		db 0FFh
		db  98h	; ò
		db 0FFh
		db  9Eh	; û
		db 0FFh
		db 0A4h	; §
		db 0FFh
		db 0AAh	; ™
		db 0FFh
		db 0B0h	; ∞
		db 0FFh
		db 0B6h	; ∂
		db 0FFh
		db 0BCh	; º
		db 0FFh
		db 0C2h	; ¬
		db 0FFh
		db 0C8h	; »
		db 0FFh
		db 0CEh	; Œ
		db 0FFh
		db 0D4h	; ‘
		db 0FFh
		db 0DAh	; ⁄
		db 0FFh
		db 0E1h	; ·
		db 0FFh
		db 0E7h	; Á
		db 0FFh
		db 0EDh	; Ì
		db 0FFh
		db 0F3h	; Û
		db 0FFh
		db 0FAh	; ˙
		db 0FFh
		db    0
		db    0
		db    6
		db    0
		db  0Dh
		db    0
		db  13h
		db    0
		db  19h
		db    0
		db  1Fh
		db    0
		db  26h	; &
		db    0
		db  2Ch	; ,
		db    0
		db  32h	; 2
		db    0
		db  38h	; 8
		db    0
		db  3Eh	; >
		db    0
		db  44h	; D
		db    0
		db  4Ah	; J
		db    0
		db  50h	; P
		db    0
		db  56h	; V
		db    0
		db  5Ch	; \
		db    0
		db  62h	; b
		db    0
		db  68h	; h
		db    0
		db  6Dh	; m
		db    0
		db  73h	; s
		db    0
		db  79h	; y
		db    0
		db  7Eh	; ~
		db    0
		db  84h	; Ñ
		db    0
		db  89h	; â
		db    0
		db  8Eh	; é
		db    0
		db  93h	; ì
		db    0
		db  98h	; ò
		db    0
		db  9Dh	; ù
		db    0
		db 0A2h	; ¢
		db    0
		db 0A7h	; ß
		db    0
		db 0ACh	; ¨
		db    0
		db 0B1h	; ±
		db    0
		db 0B5h	; µ
		db    0
		db 0B9h	; π
		db    0
		db 0BEh	; æ
		db    0
		db 0C2h	; ¬
		db    0
		db 0C6h	; ∆
		db    0
		db 0CAh	;  
		db    0
		db 0CEh	; Œ
		db    0
		db 0D1h	; —
		db    0
		db 0D5h	; ’
		db    0
		db 0D8h	; ÿ
		db    0
		db 0DCh	; ‹
		db    0
		db 0DFh	; ﬂ
		db    0
		db 0E2h	; ‚
		db    0
		db 0E5h	; Â
		db    0
		db 0E7h	; Á
		db    0
		db 0EAh	; Í
		db    0
		db 0EDh	; Ì
		db    0
		db 0EFh	; Ô
		db    0
		db 0F1h	; Ò
		db    0
		db 0F3h	; Û
		db    0
		db 0F5h	; ı
		db    0
		db 0F7h	; ˜
		db    0
		db 0F8h	; ¯
		db    0
		db 0FAh	; ˙
		db    0
		db 0FBh	; ˚
		db    0
		db 0FCh	; ¸
		db    0
		db 0FDh	; ˝
		db    0
		db 0FEh	; ˛
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db    0
		db    1
		db    0
		db    1
		db    0
		db    3
		db    6
		db    9
		db  0Ch
		db  0Fh
		db  12h
		db  15h
		db  18h
		db  1Ch
		db  1Fh
		db  22h	; "
		db  25h	; %
		db  28h	; (
		db  2Bh	; +
		db  2Eh	; .
		db  30h	; 0
		db  33h	; 3
		db  36h	; 6
		db  39h	; 9
		db  3Ch	; <
		db  3Fh	; ?
		db  41h	; A
		db  44h	; D
		db  47h	; G
		db  49h	; I
		db  4Ch	; L
		db  4Eh	; N
		db  51h	; Q
		db  53h	; S
		db  55h	; U
		db  58h	; X
		db  5Ah	; Z
		db  5Ch	; \
		db  5Eh	; ^
		db  60h	; `
		db  62h	; b
		db  64h	; d
		db  66h	; f
		db  68h	; h
		db  6Ah	; j
		db  6Ch	; l
		db  6Dh	; m
		db  6Fh	; o
		db  70h	; p
		db  72h	; r
		db  73h	; s
		db  75h	; u
		db  76h	; v
		db  77h	; w
		db  78h	; x
		db  79h	; y
		db  7Ah	; z
		db  7Bh	; {
		db  7Ch	; |
		db  7Ch	; |
		db  7Dh	; }
		db  7Eh	; ~
		db  7Eh	; ~
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Fh	; 
		db  7Eh	; ~
		db  7Eh	; ~
		db  7Dh	; }
		db  7Ch	; |
		db  7Ch	; |
		db  7Bh	; {
		db  7Ah	; z
		db  79h	; y
		db  78h	; x
		db  77h	; w
		db  76h	; v
		db  75h	; u
		db  73h	; s
		db  72h	; r
		db  70h	; p
		db  6Fh	; o
		db  6Dh	; m
		db  6Ch	; l
		db  6Ah	; j
		db  68h	; h
		db  66h	; f
		db  64h	; d
		db  62h	; b
		db  60h	; `
		db  5Eh	; ^
		db  5Ch	; \
		db  5Ah	; Z
		db  58h	; X
		db  55h	; U
		db  53h	; S
		db  51h	; Q
		db  4Eh	; N
		db  4Ch	; L
		db  49h	; I
		db  47h	; G
		db  44h	; D
		db  41h	; A
		db  3Fh	; ?
		db  3Ch	; <
		db  39h	; 9
		db  36h	; 6
		db  33h	; 3
		db  30h	; 0
		db  2Eh	; .
		db  2Bh	; +
		db  28h	; (
		db  25h	; %
		db  22h	; "
		db  1Fh
		db  1Ch
		db  18h
		db  15h
		db  12h
		db  0Fh
		db  0Ch
		db    9
		db    6
		db    3
		db    0
		db 0FDh	; ˝
		db 0FAh	; ˙
		db 0F7h	; ˜
		db 0F4h	; Ù
		db 0F1h	; Ò
		db 0EEh	; Ó
		db 0EBh	; Î
		db 0E8h	; Ë
		db 0E4h	; ‰
		db 0E1h	; ·
		db 0DEh	; ﬁ
		db 0DBh	; €
		db 0D8h	; ÿ
		db 0D5h	; ’
		db 0D2h	; “
		db 0D0h	; –
		db 0CDh	; Õ
		db 0CAh	;  
		db 0C7h	; «
		db 0C4h	; ƒ
		db 0C1h	; ¡
		db 0BFh	; ø
		db 0BCh	; º
		db 0B9h	; π
		db 0B7h	; ∑
		db 0B4h	; ¥
		db 0B2h	; ≤
		db 0AFh	; Ø
		db 0ADh	; ≠
		db 0ABh	; ´
		db 0A8h	; ®
		db 0A6h	; ¶
		db 0A4h	; §
		db 0A2h	; ¢
		db 0A0h	; †
		db  9Eh	; û
		db  9Ch	; ú
		db  9Ah	; ö
		db  98h	; ò
		db  96h	; ñ
		db  94h	; î
		db  93h	; ì
		db  91h	; ë
		db  90h	; ê
		db  8Eh	; é
		db  8Dh	; ç
		db  8Bh	; ã
		db  8Ah	; ä
		db  89h	; â
		db  88h	; à
		db  87h	; á
		db  86h	; Ü
		db  85h	; Ö
		db  84h	; Ñ
		db  84h	; Ñ
		db  83h	; É
		db  82h	; Ç
		db  82h	; Ç
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  81h	; Å
		db  82h	; Ç
		db  82h	; Ç
		db  83h	; É
		db  84h	; Ñ
		db  84h	; Ñ
		db  85h	; Ö
		db  86h	; Ü
		db  87h	; á
		db  88h	; à
		db  89h	; â
		db  8Ah	; ä
		db  8Bh	; ã
		db  8Dh	; ç
		db  8Eh	; é
		db  90h	; ê
		db  91h	; ë
		db  93h	; ì
		db  94h	; î
		db  96h	; ñ
		db  98h	; ò
		db  9Ah	; ö
		db  9Ch	; ú
		db  9Eh	; û
		db 0A0h	; †
		db 0A2h	; ¢
		db 0A4h	; §
		db 0A6h	; ¶
		db 0A8h	; ®
		db 0ABh	; ´
		db 0ADh	; ≠
		db 0AFh	; Ø
		db 0B2h	; ≤
		db 0B4h	; ¥
		db 0B7h	; ∑
		db 0B9h	; π
		db 0BCh	; º
		db 0BFh	; ø
		db 0C1h	; ¡
		db 0C4h	; ƒ
		db 0C7h	; «
		db 0CAh	;  
		db 0CDh	; Õ
		db 0D0h	; –
		db 0D2h	; “
		db 0D5h	; ’
		db 0D8h	; ÿ
		db 0DBh	; €
		db 0DEh	; ﬁ
		db 0E1h	; ·
		db 0E4h	; ‰
		db 0E8h	; Ë
		db 0EBh	; Î
		db 0EEh	; Ó
		db 0F1h	; Ò
		db 0F4h	; Ù
		db 0F7h	; ˜
		db 0FAh	; ˙
		db 0FDh	; ˝
word_2668	dw 1
word_266A	dw 0
aAbnormalProgra	db 'Abnormal program termination',0Dh,0Ah,0
		db 0
include libs/BorlandC/atexit[data].asm
include libs/BorlandC/exit[data].asm
include libs/BorlandC/files[data].asm
__heaplen	dw 0
include libs/BorlandC/__IOERROR[data].asm
		db    0
__stklen	dw 1000h
include libs/BorlandC/nearheap[data].asm
word_2864	dw 0
word_2866	dw 0
include libs/BorlandC/sysnerr[data].asm

InitStart	label byte
include libs/BorlandC/setupio[initdata].asm
InitEnd	label byte

ExitStart	label byte
ExitEnd	label byte

bdata@	label byte
; TODO: Missing clip[bss].asm (8 bytes) somewhere in there...
		db 126h dup(?)
include libs/master.lib/pal[bss].asm
include libs/master.lib/superpa[bss].asm
		db 182h dup(?)
include libs/master.lib/mem[bss].asm
		dd ?
		dd ?
		dd ?
		dd ?
include libs/BorlandC/atexit[bss].asm
edata@	label byte

seg000		ends


		end startx
