// Central BGM title definitions for TH03
// --------------------------------------

#define TH03_01 "  @–²‚Í‹ó‚ğ‰z‚¦‚Ä     "
#define TH03_02 " @ @ Selection         "
#define TH03_03 "       “Œ•û—d—ö’k        "
#define TH03_04 "     Reincarnation       "
#define TH03_05 "       Dim. Dream        "
#define TH03_06 "Tabula rasa@`‹ó”’­—  "
#define TH03_07 "@  Maniacal Princess    "
#define TH03_08 "   –²Á¸  `Lost Dream  "
#define TH03_09 "  –²Œ¶—V‹Y  `Dream War  "
#define TH03_10 "–‚–@ŒˆíI`Fight it out!"
#define TH03_11 "  @ Sailor of Time      "
#define TH03_12 "   Strawberry Crisis!!   "
#define TH03_13 "    ”ñ“ˆê–‚–@¢ŠE˜_     "
#define TH03_14 "      @–‚–@àˆ¤         "
#define TH03_15 "      @‹v‰“‚Ì–²         "
#define TH03_16 "      “Œ•û‚ÌÂ‚¢‹ó       "
#define TH03_17 "       ‰i‰“‚Ì–Œ        "
#define TH03_18 "     Maple Dream...      "
#define TH03_19 "       —ìl‚Ì‹x“ú        "
#define TH03_QT "    @@‚p‚•‚‰‚”         "
