public _ptn_sloppy_unput_before_alpha_pu
public _ptnpq_mask_unaligned_zero, _ptnpq_dots_unaligned_zero, _ptnpq_vram
_ptn_sloppy_unput_before_alpha_pu	db 0
_ptnpq_mask_unaligned_zero	dd 0
_ptnpq_dots_unaligned_zero	dd 0
_ptnpq_vram	dd 4 dup (0)
