public _ALPHABET_A
public _ALPHABET_SPACE, _ALPHABET_LEFT, _ALPHABET_RIGHT, _ALPHABET_ENTER

if BINARY eq 'E'
	public _ALPHABET_KANJI_FMT_0, _ALPHABET_KANJI_FMT_1
	public _ALPHABET_KANJI_FMT_2, _ALPHABET_KANJI_FMT_3
	_ALPHABET_KANJI_FMT_0	db '%c%c',0
	_ALPHABET_A		db 'ÇÅ',0
	_ALPHABET_KANJI_FMT_1	db '%c%c',0
	_ALPHABET_KANJI_FMT_2	db '%c%c',0
	_ALPHABET_KANJI_FMT_3	db '%c%c',0
else
	_ALPHABET_A		db 'ÇÅ',0
endif
_ALPHABET_SPACE	db 'SP',0
_ALPHABET_LEFT 	db 'Å©',0
_ALPHABET_RIGHT	db 'Å®',0
_ALPHABET_ENTER	db 'èI',0
