public _ALPHABET_A
public _ALPHABET_SPACE, _ALPHABET_LEFT, _ALPHABET_RIGHT, _ALPHABET_ENTER

if BINARY eq 'E'
	public _ALPHABET_KANJI_FMT_0, _ALPHABET_KANJI_FMT_1
	public _ALPHABET_KANJI_FMT_2, _ALPHABET_KANJI_FMT_3
	_ALPHABET_KANJI_FMT_0	db '%c%c',0
	_ALPHABET_A		db 'ａ',0
	_ALPHABET_KANJI_FMT_1	db '%c%c',0
	_ALPHABET_KANJI_FMT_2	db '%c%c',0
	_ALPHABET_KANJI_FMT_3	db '%c%c',0
else
	_ALPHABET_A		db 'ａ',0
endif
_ALPHABET_SPACE	db 'SP',0
_ALPHABET_LEFT 	db '←',0
_ALPHABET_RIGHT	db '→',0
_ALPHABET_ENTER	db '終',0

public _REGIST_HEADER_PLACE, _REGIST_HEADER_NAME
public _REGIST_HEADER_POINTS, _REGIST_HEADER_STAGE_ROUTE
public _REGIST_PLACE_0, _REGIST_PLACE_1, _REGIST_PLACE_2, _REGIST_PLACE_3
public _REGIST_PLACE_4, _REGIST_PLACE_5, _REGIST_PLACE_6, _REGIST_PLACE_7
public _REGIST_PLACE_8, _REGIST_PLACE_9
public _REGIST_STAGE_MAKAI, _REGIST_STAGE_JIGOKU, _REGIST_STAGE_ROUTE_DASH
_REGIST_HEADER_PLACE    	db '　霊　位　',0
_REGIST_HEADER_NAME        	db '　　名　　前　　',0
_REGIST_HEADER_POINTS     	db '　　得　　点　　',0
_REGIST_HEADER_STAGE_ROUTE	db 'ステージ・ルート',0
_REGIST_PLACE_0	db '　靈　神　',0
_REGIST_PLACE_1	db '太元帥明王',0
_REGIST_PLACE_2 db '　天　仙　',0
_REGIST_PLACE_3	db '　神　仙　',0
_REGIST_PLACE_4	db '　地　仙　',0
_REGIST_PLACE_5	db '　人　仙　',0
_REGIST_PLACE_6	db '　仙　女　',0
_REGIST_PLACE_7	db '陰　陽　師',0
_REGIST_PLACE_8	db '靈　媒　師',0
_REGIST_PLACE_9	db '修　業　者',0
_REGIST_STAGE_MAKAI 	db '魔界',0
_REGIST_STAGE_JIGOKU	db '地獄',0
_REGIST_STAGE_ROUTE_DASH	db '－',0
if BINARY eq 'E'
	public _REGIST_ROUTE_FMT
	_REGIST_ROUTE_FMT	db '%c%c',0

	public _ALPHABET_SPACE_0, _ALPHABET_LEFT_0
	public _ALPHABET_RIGHT_0, _ALPHABET_ENTER_0, _ALPHABET_KANJI_FMT_4
	_ALPHABET_SPACE_0	db 'SP',0
	_ALPHABET_LEFT_0 	db '←',0
	_ALPHABET_RIGHT_0	db '→',0
	_ALPHABET_ENTER_0	db '終',0
	_ALPHABET_KANJI_FMT_4	db '%c%c',0
endif
