public _REGIST_NAME_BLANK, _REGIST_NAME_SPACES, _SCOREDAT_MAGIC
_REGIST_NAME_BLANK	db 'ÅQÅQÅQÅQÅQÅQÅQÅQ',0
if BINARY eq 'M'
	public _regist_jump_to_enter
	_regist_jump_to_enter	db 0
endif
_REGIST_NAME_SPACES	db 'Å@Å@Å@Å@Å@Å@Å@Å@',0
_SCOREDAT_MAGIC	db 'HISCORE',0

public _REGIST_TITLE_RANKS
_REGIST_TITLE_RANKS	label dword
	dd _REGIST_TITLE_RANK_EASY
	dd _REGIST_TITLE_RANK_NORMAL
	dd _REGIST_TITLE_RANK_HARD
	dd _REGIST_TITLE_RANK_LUNATIC
