public _SCOREDAT_ROUTE_NONE, _scoredat_name_default
public _SCOREDAT_MAGIC_0, _SCOREDAT_MAGIC_1
public _SCOREDAT_FN_EASY_0, _SCOREDAT_FN_EASY_1
public _SCOREDAT_FN_NORMAL_0, _SCOREDAT_FN_NORMAL_1
public _SCOREDAT_FN_HARD_0, _SCOREDAT_FN_HARD_1
public _SCOREDAT_FN_LUNATIC_0, _SCOREDAT_FN_LUNATIC_1

_SCOREDAT_ROUTE_NONE		db '無',0
_scoredat_name_default		db '東方★靈異伝　　',0

if BINARY eq 'E'
	public _FOPEN_WB, _FOPEN_RB
	public _SCOREDAT_ERROR_NOT_FOUND, _SCOREDAT_ERROR_INVALID
	_SCOREDAT_MAGIC_0	db 'HISCORE',0
	_SCOREDAT_FN_EASY_0   	db 'REYHIES.DAT',0
	_SCOREDAT_FN_NORMAL_0 	db 'REYHINO.DAT',0
	_SCOREDAT_FN_HARD_0   	db 'REYHIHA.DAT',0
	_SCOREDAT_FN_LUNATIC_0	db 'REYHILU.DAT',0
	_FOPEN_WB		db 'wb',0
	_SCOREDAT_FN_EASY_1	db 'REYHIES.DAT',0
	_SCOREDAT_FN_NORMAL_1	db 'REYHINO.DAT',0
	_SCOREDAT_FN_HARD_1	db 'REYHIHA.DAT',0
	_SCOREDAT_FN_LUNATIC_1	db 'REYHILU.DAT',0
	_FOPEN_RB		db 'rb',0
	_SCOREDAT_ERROR_NOT_FOUND	db 'ファイルがみつかんない',0
	_SCOREDAT_MAGIC_1	db 'HISCORE',0
	_SCOREDAT_ERROR_INVALID		db 'ファイルが違う！',0
else
	_SCOREDAT_MAGIC_1 label byte
	_SCOREDAT_MAGIC_0	db 'HISCORE',0
	_SCOREDAT_FN_EASY_1 label byte
	_SCOREDAT_FN_EASY_0   	db 'REYHIES.DAT',0
	_SCOREDAT_FN_NORMAL_1 label byte
	_SCOREDAT_FN_NORMAL_0 	db 'REYHINO.DAT',0
	_SCOREDAT_FN_HARD_1 label byte
	_SCOREDAT_FN_HARD_0   	db 'REYHIHA.DAT',0
	_SCOREDAT_FN_LUNATIC_1 label byte
	_SCOREDAT_FN_LUNATIC_0	db 'REYHILU.DAT',0
endif
