static const int SHAPE_INVINCIBILITY_COUNT = 4;
#define SHAPE_INVINCIBILITY_W 8
#define SHAPE_INVINCIBILITY_H 8

extern const dot_rect_t(
	SHAPE_INVINCIBILITY_W, SHAPE_INVINCIBILITY_H
) sSHAPE_INVINCIBILITY[SHAPE_INVINCIBILITY_COUNT];
