ENEMY_DROPS label byte
	db IT_POWER, IT_POINT, IT_POWER, IT_POWER, IT_POINT, IT_POINT, IT_POWER, IT_POINT
	db IT_POWER, IT_POINT, IT_POINT, IT_POINT, IT_POWER, IT_POWER, IT_POWER, IT_POINT
	db IT_POWER, IT_POINT, IT_POINT, IT_POWER, IT_POWER, IT_POINT, IT_POWER, IT_POINT
	db IT_POWER, IT_POINT, IT_POINT, IT_POINT, IT_POINT, IT_POWER, IT_POINT, IT_POINT
	db IT_POWER, IT_POWER, IT_POINT, IT_POINT, IT_POWER, IT_POINT, IT_POWER, IT_POINT
	db IT_POINT, IT_POINT, IT_POWER, IT_POWER, IT_POINT, IT_POINT, IT_POWER, IT_POINT
	db IT_POINT, IT_POWER, IT_POWER, IT_POINT, IT_POWER, IT_POINT, IT_POINT, IT_POWER
	db IT_POWER, IT_POINT, IT_POINT, IT_POINT, IT_POWER, IT_POINT, IT_POWER, IT_BIGPOWER
