// Central BGM title definitions for TH04
// --------------------------------------

#define TH04_01 " Œ¶‘z‹½  ` Lotus Land Story"
#define TH04_02 "       Witching Dream       "
#define TH04_03 "       Selene's light       "
#define TH04_04 "‘•üí@` Decoration Battle"
#define TH04_05 "      Break the Sabbath     "
#define TH04_06 " g‹¿‹È  ` Scarlet Phoneme "
#define TH04_07 "         Bad Apple!!        "
#define TH04_08 "  —ìí@` Perdition crisis "
#define TH04_09 "      ƒAƒŠƒXƒ}ƒGƒXƒeƒ‰      "
#define TH04_10 "  ­—ãY‘z‹È@` Capriccio  "
#define TH04_11 " ¯‚ÌŠí@` Casket of Star  "
#define TH04_12 "         Lotus Love         "
#define TH04_13 "–°‚ê‚é‹°•| `Sleeping Terror"
#define TH04_14 "         Dream Land         "
#define TH04_15 "  —H–²@` Inanimate Dream  "
#define TH04_16 "    ‹Ö‚¶‚´‚é‚ğ‚¦‚È‚¢—V‹Y    "
#define TH04_17 "ƒƒCƒhŒ¶‘z@` Icemilk Magic"
#define TH04_18 " ‚©‚í‚¢‚¢ˆ«–‚@` Innocence "
#define TH04_19 "            Days            "
#define TH04_20 "          Peaceful          "
#define TH04_21 "       Arcadian Dream       "
#define TH04_22 "         Œ¶‘z‚ÌZl         "
#define TH04_QT "      @@‚p‚•‚‰‚”          "
