#include "platform.h"
#include "master.hpp"
#include "th03/common.h"
#include "th03/playchar.hpp"
#include "th03/score.hpp"
#include "th03/resident.hpp"
#include "th03/formats/cfg.hpp"
#include "th03/formats/cfg_lres.cpp"
