ITEM_TYPE_PATNUM label word
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_POWER
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_POINT
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_DREAM
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_BIGPOWER
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_BOMB
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_1UP
	dw	ITEM_TYPE_PATNUM_OFFSET + IT_FULLPOWER
