ITEM_TYPE_PATNUM label word
	dw	PAT_ITEM + IT_POWER
	dw	PAT_ITEM + IT_POINT
	dw	PAT_ITEM + IT_DREAM
	dw	PAT_ITEM + IT_BIGPOWER
	dw	PAT_ITEM + IT_BOMB
	dw	PAT_ITEM + IT_1UP
	dw	PAT_ITEM + IT_FULLPOWER
