// Central BGM title definitions for TH05
// --------------------------------------

#define TH05_01 "   怪綺談　～ Mystic Square   "
#define TH05_02 "         Dream Express        "
#define TH05_03 "    魔法陣　～ Magic Square   "
#define TH05_04 "           夢想時空           "
#define TH05_05 "   霊天　～ Spiritual Heaven  "
#define TH05_06 "       Romantic Children      "
#define TH05_07 "     プラスチックマインド     "
#define TH05_08 "        メイプルワイズ        "
#define TH05_09 "禁断の魔法  ～ Forbidden Magic"
#define TH05_10 " 真紅の少女　～ Crimson Dead!!"
#define TH05_11 " 裏切りの少女　～ Judas Kiss  "
#define TH05_12 "      the Last Judgement      "
#define TH05_13 " 悲しき人形　～ Doll of Misery"
#define TH05_14 "  世界の果て　～ World's End  "
#define TH05_15 "  神話幻想　～ Infinite Being "
#define TH05_16 "      不思議の国のアリス      "
#define TH05_17 "    the Grimoire of Alice     "
#define TH05_18 "             神社             "
#define TH05_19 "           Endless            "
#define TH05_20 "         久遠の楽園           "
#define TH05_21 "        Mystic Dream          "
#define TH05_22 "      Peaceful Romancer       "
#define TH05_23 "        魂の休らむ所          "
